### ISSUE TITLE
[Improvement][Core]: ams tracer should report snapshot information even if no new file is submitted

### ISSUE THREAD

**Issue by hameizi** [NetEase/arctic#1013]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In the default configuration, flink submits empty snapshots with no new files to arctic when there is no data. The ams file cache ensures the continuity of snapshots. If the empty snapshot information is not cached, subsequent tracer snapshot submission fails. This affects the frequency of optimize, which may affect the visibility of hive table data (because it is determined by full optimize). So ams tracer should report snapshot information even if no new file is submitted.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@hameizi Could you add the reason why this improvement is needed?
