### ISSUE TITLE
[Spark][Bug]: Create table like cannot display the primary key information when using kyuubi

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#1027]
### What happened?

Create table like cannot display the primary key information when using Kyuubi.
The problem is that Kyuubi modified the logical plan, so we cannot execute our logic

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

Spark

### How to reproduce

step1: Execute create table like command to create a keyed table in kyuubi
step2: Execute describe table command

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
Not only just lack of primary key information but also the table is not registered to AMS. The table was created as a hive table.
