### ISSUE TITLE
[Subtask]: [Improvement][Flink]:  Make sure the LogKafka SQL job compatibility after refactor

### ISSUE THREAD

**Issue by zstraw** [NetEase/arctic#1029]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Description

- Sql in deprecated LogKafkaSource api should be able to restore from ckp after bumping arctic-flink to new version.
- annotate the deprecated version and removed version.
- Adopt LogStoreAddress config in LogKafkaSourceBuilder.

### Parent issue

#969 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
@zstraw Maybe we should consider this scenario:
1. Build an arctic 0.4.0 version flink job, e.g., datagen -> KeyBy -> arctic(log,file) -> arctic(log) -> print
2. Build a new arctic flink runtime package(0.4.1), and restore the flink application from a checkpoint with the new version jar.
3. Friendly prompt information to users on how to upgrade the flink job.
4. Upgrade stateful flink jobs with simplified configuration.

**Comment by zstraw** [comment]
> @zstraw Maybe we should consider this scenario:
> 
> 1. Build an arctic 0.4.0 version flink job, e.g., datagen -> KeyBy -> arctic(log,file) -> arctic(log) -> print
> 2. Build a new arctic flink runtime package(0.4.1), and restore the flink application from a checkpoint with the new version jar.
> 3. Friendly prompt information to users on how to upgrade the flink job.
> 4. Upgrade stateful flink jobs with simplified configuration.

IMO, the job with 0.4.1 can not aware the version of states in operator, but after flink throwing exception. So the only way to prompt user is document.

**Comment by zstraw** [comment]
Resolve by 80961e96b9a442ef592046abe61ffe0ff7b4f4f0
