### ISSUE TITLE
[Improvement][Flink]: Support the Job which sinks to Arctic restoring after changing parallelism

### ISSUE THREAD

**Issue by zstraw** [NetEase/arctic#1034]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The Job which sinks to Arctic should be restored after changing parallelism.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@zstraw Did you meet any exceptions when you restore the flink job after changing parallelism?
Can you add some description about that?

**Comment by YesOrNo828** [comment]
I think this issue is duplicated with #1233, so I'll close it.
