### ISSUE TITLE
[Bug]: When using native iceberg's hive catalog, the hive-site configuration  cannot be configured in the dashboard

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1049]
### What happened?

![image](https://user-images.githubusercontent.com/109209550/216263171-ea6b55c4-7886-4f80-b331-41be382e05a8.png)
As you can see, when I try to use iceberg's hive catalog mode, I cannot configure the hive-site configuration, so I cannot connect to the hive meta store to get the hive metadata information

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

1.Create a catalog configuration as shown above.
2.Load catalog.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
You should use 
![image](https://user-images.githubusercontent.com/7732224/218397381-306143a0-76b6-4017-b897-ed5b8413d581.png)
this property to set a hive catalog

**Comment by baiyangtx** [comment]
This is not a bug, but the way to use the custom type meta-store. 
Change to an improvement issue. https://github.com/NetEase/arctic/issues/1109
