### ISSUE TITLE
[Bug]: Spark reads the timestamp field eight hours longer than the actual Flink engine writes timestamp

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/arctic#1062]
### What happened?

Spark reads the timestamp field eight hours longer than the actual Flink engine writes the timestamp records.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink, Spark

### How to reproduce

1. create catalog arctic With ('type'='arctic','metastore.url'='thrift://***:18312/mix_iceberg_catalog_simple');
2. create table arctic.flink_test.pulsar_pk (id int, name string, dt timestamp, primary key(id) not enforced) with ('log-store.enabled'='true','log-store.type'='pulsar','log-store.topic'='without_partition','log-store.address'='pulsar://***:16650','properties.pulsar.admin.adminUrl'='http://***:8180');
3. CREATE TABLE cdc_source(
  id      INT,
  name    STRING,
  op_time STRING
) WITH (
    'connector' = 'socket',
    'hostname' = 'localhost',
    'port' = '9999',
    'format' = 'changelog-csv',
    'changelog-csv.column-delimiter' = '|'
);
4. insert into arctic.flink_test.kafka_pk /*+ OPTIONS('arctic.emit.mode'='file') */
 SELECT id,
        name,
        CAST(TO_TIMESTAMP(op_time) AS TIMESTAMP(6)) ts
 FROM cdc_source;

open a socket producer: nc -lk 9999 
according to the [quick demo](https://arctic.netease.com/ch/quickstart/quick-demo/#step-2-execute-flink-upsert), write three records.
```
INSERT|4|rock|2022-07-02 09:01:00
INSERT|5|jack|2022-07-02 12:11:40
INSERT|6|mars|2022-07-02 11:19:10
```

5.  SELECT * FROM arctic.flink_test.pulsar_pk /*+ OPTIONS('arctic.read.mode'='file','scan.startup.mode'='earliest') */;
6. Open the Arctic web dashboard, open a Terminal tab, use mix_iceberg_catalog_simple catalog, and edit the SQL: select * from flink_test.pulsar_pk;

### Anything else

![popo_2023-02-07  11-10-49](https://user-images.githubusercontent.com/6017591/217138747-78bfb1c5-1b11-414e-a3aa-b476aa031a22.jpg)
![popo_2023-02-07  11-12-04](https://user-images.githubusercontent.com/6017591/217138991-b0cae552-daa6-4bfd-87be-1602d0de0cd8.jpg)
![popo_2023-02-07  11-12-29](https://user-images.githubusercontent.com/6017591/217138995-1a69da63-20be-4fed-8b0d-e768ccac3e5d.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
The Flink engine converts string type to long type without a timezone, and writes to parquet as long.
The Spark engine reads the long value from the parquet file as a UTC0 time, and converts it to local timestamp by local  timezone.

The AMS Terminal should support config spark properties in the local model.

```
arctic.ams.terminal.backend: local
arctic.ams.terminal.local.spark.driver.extraJavaOptions:  -Duser.timezone=UTC
arctic.ams.terminal.local.spark.executor.extraJavaOptions:  -Duser.timezone=UTC
arctic.ams.terminal.local.spark.sql.session.timeZone: UTC
arctic.ams.terminal.local.spark.sql.iceberg.handle-timestamp-without-timezone=false
```

**Comment by baiyangtx** [comment]
@hellojinsilei CC
