### ISSUE TITLE
[Spark][Bug]: The read and write authentication user are different in Spark when using mixed Iceberg format

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#1069]
### What happened?

When using mixed Iceberg format, Spark writer using the authentication user in SparkContext,  but reader using the authentication user in arctic. So the written file cannot be read

![image](https://user-images.githubusercontent.com/52364847/217198949-28601577-1c9c-4a22-8c21-0bb716b1c90f.png)

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

Spark

### How to reproduce

step1: use mixed iceberg catalog and configure authenticated users in the arctic
step2: use different authentication users to write data using spark
step3: execute select

tips:The permission of the read authentication user is smaller than that of the write authentication user

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
The problem disappear after kyuubi restart.
