### ISSUE TITLE
[BUG]: The expire snapshot and the orphan file clean scan related files from metadata

### ISSUE THREAD

**Issue by hzluting** [NetEase/arctic#1105]
### Description

The snapshot expires and the TTL scans files from metadata with TableScan API.
The orphan file clean will check whether the files in the change store are also indexed by the base store.

### Use case/motivation

Now, the expire clean checks useless files by scan files from the file info cache, making the data consistency rely too much on the correctness of the file info cache.
The orphan file clean doesn't consider the same file in the change store and the base store.

### Describe the solution

Load MetadataTableType.ALL_MANIFESTS to get all the content file entries in manifest files, like what org.apache.iceberg.spark.actions.BaseSparkAction#buildValidDataFileDF does.

### Related issues

#883 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@hzluting  Does this feature fix the bug that expiring table snapshot and cleaning orphan files will remove files still needed when using the AMS file cache?

**Comment by hzluting** [comment]
> @hzluting Does this feature fix the bug that expiring table snapshot and cleaning orphan files will remove files still needed when using the AMS file cache?
> 
> If yes, we may change issue type to `BUG`.

Yes, I will change it.
