### ISSUE TITLE
[Bug]: Full optimizing doubles the data after change TableProperties `self-optimizing.group`

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#1119]
### What happened?

After changed ArcticTable's `self-optimizing.group`, the next full optimizing doubles the data occasionally.

There are 1005 files before full optimizing, but 2010 files are involved in the full optimizing.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/103108928/218976361-2aa1e9d9-ebdb-40f6-a3b4-75cf7de71dd8.png">

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/103108928/218975356-3c663000-fe48-479e-9244-9f2de4cb90b0.png">

``

### Affects Versions

master/0.3.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

This problem happens occasionally, and it's hard to reproduce.

When we change the `self-optimizing.group`, and both optimize groups are running the full optimize plan for this table concurrently, this problem will occur.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
Relevant log output
<img width="797" alt="image" src="https://user-images.githubusercontent.com/103108928/218977656-a049823d-c45a-4f15-afd7-29e2a755614d.png">

**Comment by zhoujinsong** [comment]
As the bug leads to the incorrect data problem, I do give it a `critical` priority.

**Comment by zhoujinsong** [comment]
> Relevant log output <img alt="image" width="797" src="https://user-images.githubusercontent.com/103108928/218977656-a049823d-c45a-4f15-afd7-29e2a755614d.png">

I am wondering if it is possible that the optimize tasks under different groups of the same table can be merged into one optimize history?

**Comment by wangtaohz** [comment]
> I am wondering if it is possible that the optimize tasks under different groups of the same table can be merged into one optimize history?

Yes, it is possible. When committing, it collects all prepared tasks without any other checking.

```
  /**
   * Get tasks which is ready to commit (only if all tasks in a table is ready).
   *
   * @return map partition -> tasks of partition
   */
  public Map<String, List<OptimizeTaskItem>> getOptimizeTasksToCommit() {
    tasksLock.lock();
    try {
      Map<String, List<OptimizeTaskItem>> collector = new HashMap<>();
      for (OptimizeTaskItem optimizeTaskItem : optimizeTasks.values()) {
        String partition = optimizeTaskItem.getOptimizeTask().getPartition();
        if (!optimizeTaskItem.canCommit()) {
          collector.clear();
          break;
        }
        optimizeTaskItem.setFiles();
        collector.computeIfAbsent(partition, p -> new ArrayList<>()).add(optimizeTaskItem);
      }
      return collector;
    } finally {
      tasksLock.unlock();
    }
  }
```
