### ISSUE TITLE
[Bug]: The keytab file downloaded from the Catalog management dashboard is incorrect

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1120]
### What happened?

![image](https://user-images.githubusercontent.com/109209550/219012869-9c6b3adc-eb7c-4d22-b792-e80f239977a3.png)
As shown, when I upload the correct keytab file, and then loads the catalog properly, but when I download the file that way and upload it again, it does not load the catalog properly and throws a kerberos authentication exception

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

1.Create a new Catalog Use Kerberos authentication and upload the correct authentication file.
2.Download the keytab file for this Catalog and then re-upload the file you just downloaded.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@Aireed @hameizi
Do you have time to address and fix this bug?
