### ISSUE TITLE
[Bug]: with Kuyybui 1.6.1,  data duplication even if there is a primary key table with upsert enabled.

### ISSUE THREAD

**Issue by GavinH1984** [NetEase/arctic#1129]
### What happened?

env: 
kyuubi-1.6.1 + arctic-0.4.0 + spark3.1.3 + hadoop3.2.4

problem description:
with kyuubi 1.6.1, define primary key table with write.upsert.enabled, also config the spark.sql.arctic.check-source-data-uniqueness.enabled to ture, there will have duplicate data for the same key, this is not expected. 

if using the spark-sql directly, the result is correct.

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

Spark

### How to reproduce

#connect to kyuubi
```shell
beeline -u "jdbc:hive2://localhost:10009/default?spark.sql.arctic.check-source-data-uniqueness.enabled=ture;"
```

```sql
# use arctic catalog;
use arctic_catalog;

# swith to relate database
use arctic_demo;

# create primary key table
CREATE TABLE event(
    id int, 
data string, 
day string, 
primary key(id)
)
using arctic partitioned by (day)
TBLPROPERTIES ('write.upsert.enabled' = 'true');

#insert data with same keys and difference data.
insert into event values(1,'test1','20230101');
insert into event values(1,'test2','20230101');

# query the result
select * from event;

# expected result:
# only return one record with test2.

# actual result: 
# return tow record with the same key: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@baiyangtx
It seems that Kyuubi has modified the execution process of the insert statement, causing the upsert mode not to work properly, do you have time to take a look?

**Comment by hellojinsilei** [comment]
The word ’true‘  is misspelled

**Comment by baiyangtx** [comment]
Spark properties are misspelled.
