### ISSUE TITLE
[Bug]: The page repeat display container info

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#1142]
### What happened?

![image](https://user-images.githubusercontent.com/16421989/220586278-3e215276-6f06-4fa0-a0b9-b229804ac38d.png)

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

Multiple clicks on Settings > Container Settings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@huiyuanz 
I have reproduced the problem in my test environment，do you have time to fix this bug?

**Comment by huiyuanz** [comment]
> @huiyuanz I have reproduced the problem in my test environment，do you have time to fix this bug?

ok I will fix this today
