### ISSUE TITLE
[Bug]: Reuse containers in ManifestReader will cause one IcebergFileEntry in the Java map covered by another

### ISSUE THREAD

**Issue by HuangFru** [NetEase/arctic#1143]
### What happened?

I'm trying to develop the Table Statistics feature in Arctic-Trino #1166. When I add the includeColumnStats builder in the planning stage in Arctic-Core, I found the statistics information is wrong in the map which is used to group files by partition.

When Java map stores an object which is not immutable, it only stores references to objects. So if the object changed, the value in the map will change too. When planning tasks in the change store, we get the entries of manifest by rows() method in ManifestReadTask in BaseEntriesTable. This method calls the open() method in ManifesrReader which will reuse containers. Once it reuses the container, the value in the Java map will be changed for it did not create a new object but just reuse the last object. So the next value's statistics will cover the last one's statistics.

This is the map mentioned above:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/68625618/220580686-b06d8688-77f1-48f5-a134-b7fd8d6099ba.png">

This is the rows() method mentioned above and where we call it:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/68625618/220581379-868d8e74-8a4e-40e4-aa83-9fdf47bb2f04.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/68625618/220581452-9c85219a-8b1c-408e-a744-e506d2c3c68e.png">

This is the open() method mentioned above:
<img width="704" alt="截屏2023-02-22 17 35 18" src="https://user-images.githubusercontent.com/68625618/220580422-819bcf4a-8b14-428d-ab5d-d003d427f08a.png">

### Affects Versions

May not affect in master, but it will.

### What engines are you seeing the problem on?

Core

### How to reproduce

Because we didn't use the statistics information in the code after the map was created, there's no problem for now. But we're going to develop the Table statistics feature, so it will be a problem.
About reproduce:
Just write some files into a table's change store and debug the plan task stage adding debug breakpoint to the map mentioned above and watching it.

Here's my debug information:
This is 5-I-2-00000-0-0000000002.parquet which is first put in the map:
![image](https://user-images.githubusercontent.com/68625618/220600908-144fa78b-2cf6-4135-ae36-8c033f6a42bd.png)
This is 4-I-2-00000-0-0000000001.parquet which is put in the map after 5-I-2-00000-0-0000000002.parquet:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/68625618/220601478-e7a7e4be-b9a6-43e3-b883-a35bd96ae98a.png">

We can see that they have the same object about statistics. When the latter value was put in, the former one's statistics information will be covered.

### Relevant log output

```shell
See the pictures in 'How to reproduce'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@HuangFru  I have searched all the issues and have not found the one about the `Table Statistics feature in Arctic-Trino`.
Have I missed it?

**Comment by HuangFru** [comment]
@zhoujinsong There's no issue for now. I'll open it later.
