### ISSUE TITLE
[Improvement]: When the Optimizer job under Flink environment is canceled during runtime, it cannot exit smoothly.

### ISSUE THREAD

**Issue by iTodoo** [NetEase/arctic#1152]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When the Optimizer job under Flink environment is canceled during runtime, it cannot exit smoothly.

### How should we improve?

Use variables to optimize the while loop logic in the run method of the FlinkConsumer class in the arctic-optimizer module. When the user cancels the job, control the loop variable to be false to allow the while loop to exit in a timely manner.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
Thanks for your report!

I will be glad to review the PR.
