### ISSUE TITLE
[Improvement]:  arctic sink task can't restore from checkpoint after modify sink parallelism

### ISSUE THREAD

**Issue by Aireed** [NetEase/arctic#1233]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In some production scenarios, the failure to account for traffic bursts leads to backpressure of tasks at a certain time. We need to increase the concurrency of tasks to solve this problem. Currently it is not possible to recover from checkpoint due to the way the state is implemented.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
![image](https://user-images.githubusercontent.com/6017591/227157446-3aa84c30-f416-4ec1-a606-e694cd4a46b0.png)
Thanks, @Aireed for mentioning this improvement. I met this exception after reducing or increasing the config option `sink. parallelism` and then restoring the flink job from a checkpoint.
