### ISSUE TITLE
[Improvement]: Support setting the Flink dependency version of the optimizer with the maven profile

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/arctic#1272]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

As discussion #645 describes, the Arctic optimizer is dependent on Flink 1.12 now.
If the user wants to run the optimizer with another version Flink environment, he needs to change the pom manually.
We may support setting the Flink dependency version of the optimizer with the maven profile to simplify the operation.

BTW, I do suggest changing the default build version of Flink to 1.14 or higher.

### How should we improve?

Add profiles in optimizer/pom.xml to support setting different Flink dependency versions including 1.12/1.14/1.15.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tobehardest** [comment]
Hey, i want to try this out can you assign it to me?

**Comment by zhoujinsong** [comment]
Sure, and thanks a lot for your work!

**Comment by shidayang** [comment]
@tobehardest Are you still following this issue?

**Comment by zhoujinsong** [comment]
> 、
> 
> > @tobehardest你还在关注这个问题吗？
> 
> I have a lot of things to do recently, and I can't finish it for the time being. Maybe can assign this task to other people?

OK, In that case, I will unassign it, and the issue will remain open for all community developers to contribute.
