### ISSUE TITLE
[Bug]: Some deleted records came back after Self-Optimizing for the KeyedTable

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#1319]
### What happened?

I have a KeyedTable(Mixed Hive Format) with a flink job writing into it.

I find some deleted records came back after Major Self-Optimizing, breaking the data consistency.

### Affects Versions

master/0.3.*,master/0.4.*

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. create a KeyedTable(Mixed Hive/Iceberg Format)
2. insert overwrite some records into the Base Store, including the record id = 1, making these files' size > 16M
3. disable Self-Optimizing
4. update record id = 1 (Change Store)
5. update record id = 1 (Change Store)
6. delete record id = 1 (Change Store)
7. enable Self-Optimizing
8. After Minor Optimizing and Major Optimizing, select by MOR, and the record id = 1 could be found from the result, which is expected to be deleted

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
Major Self-Optimizing deletes the pos-delete files when committing if there are no output data files, however, these pos-delete files may be related to the other files not involved in this Major Self-Optimizing, so they shouldn't be deleted.

If we delete the pos-delete files after Major Self-Optimizing, these records deleted by them will come back.

**Comment by zhoujinsong** [comment]
@wangtaohz 
Hi,
This bug makes me think about if we should just leave the removing delete files job to the iceberg operation.

**Comment by wangtaohz** [comment]
> This bug makes me think about if we should just leave the removing delete files job to the iceberg operation.

Yes, deleting files explicitly brings risks.

**Comment by wangtaohz** [comment]
For Minor-Optimizing, we replace delete-files with new delete-files, these delete-files must be deleted explicitly, since iceberg will not delete them implicitly.
