### ISSUE TITLE
[Bug]: jacoco-maven-plugin report EOFException in Flink Module CI

### ISSUE THREAD

**Issue by lklhdu** [NetEase/arctic#1330]
### What happened?

When running CI Test program, the Flink module encounters EOFException which is reported by jacoco-maven-plugin.
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/49940747/231157288-bb5aeb3b-028c-4870-9bc2-0f0c03dc1414.png">

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
duplicate with #1364
