### ISSUE TITLE
[Bug]: Can't deserialize arctic log queue message due to it does not contain magic number.

### ISSUE THREAD

**Issue by luohaifang** [NetEase/arctic#1377]
### What happened?

**running flink job:** 
```
create table myarctic.myarctic_s3_db.log_table (
    msgId string, 
    bizId string, 
    primary key (msgId) not enforced 
) with ( 
    'log-store.enabled' = 'true', 
    'log-store.type' = 'kafka', 
    'log-store.topic' = 'arctic-log', 
    'log-store.address' = 'xx1:9092,xx2:9092,xx3:9092', 
    'arctic.read.mode' = 'log', 
    'properties.group.id' = 'arctic' 
); 
select * from myarctic.myarctic_s3_db.log_table;
```

**Then insert a piece of data into the topic:** 
```
CREATE TABLE sinkTB (
  msgId STRING,
  bizId STRING,
  PRIMARY KEY (msgId) NOT ENFORCED
) WITH (
  'connector' = 'upsert-kafka',
  'topic' = 'arctic-log',
  'properties.bootstrap.servers' = 'xx1:9092,xx2:9092,xx3:9092',
  'key.format' = 'json',
  'value.format' = 'json'
);
insert into sinkTB
select   'A1001' as msgId,
  'data1' as bizId;
```

**Error reported in 'select * from myarctic.myarctic_s3_db.log_table':**
```
Caused by: java.lang.UnsupportedOperationException: Can't deserialize arctic log queue message due to it does not contain magic number.
	at com.netease.arctic.flink.read.source.log.kafka.LogKafkaPartitionSplitReader.convertToLogRecord(LogKafkaPartitionSplitReader.java:207)
	at com.netease.arctic.flink.read.source.log.kafka.LogKafkaPartitionSplitReader.readNormal(LogKafkaPartitionSplitReader.java:149)
	at com.netease.arctic.flink.read.source.log.kafka.LogKafkaPartitionSplitReader.fetch(LogKafkaPartitionSplitReader.java:127)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:142)
	... 6 more
```

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

AMS, Flink

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
Thanks for your contribution!

In the Arctic, the log store can only be read and written through the arctic-flink-connector because Arctic has its own log message format, which can only be recognized by the Arctic Flink Connector.

The reason why Arctic encapsulates its own log message format is to support a series of log store-based functionalities, such as consistent reads.

If you want to learn more, please refer to https://arctic.netease.com/ch/flink/hidden-kafka/.

**Comment by luohaifang** [comment]
thank you for your reply.

> Thanks for your contribution!
> 
> In the Arctic, the log store can only be read and written through the arctic-flink-connector because Arctic has its own log message format, which can only be recognized by the Arctic Flink Connector.
> 
> The reason why Arctic encapsulates its own log message format is to support a series of log store-based functionalities, such as consistent reads.
> 
> If you want to learn more, please refer to https://arctic.netease.com/ch/flink/hidden-kafka/.
