### ISSUE TITLE
[Bug]: Incorrect data synchronization caused the data of the arctic base table to be overwritten

### ISSUE THREAD

**Issue by hameizi** [NetEase/arctic#1378]
### What happened?

The arctic base table was overwritten due to incorrect data synchronization after an empty hive table was upgraded to an arctic table. Because empty hive tables don't have full 'table.partition-properties' when upgraded, But we need 'hive-location' and 'transient-time' in 'table.partition-properties' to decide if we want to sync our data

### Affects Versions

0.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Causing data consistency issues, classified as critical.
