### ISSUE TITLE
[Bug]: Occur NPE when Iceberg version upgrade to 1.1.0

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#1380]
### What happened?

Iceberg version upgrade to 1.1.0, I meet the error.

relevant PR #989 

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Relevant log output

```shell
2023-04-19 18:39:16,966 ERROR [Metastore Scheduled Check Worker 5] [com.netease.arctic.ams.server.optimize.OptimizeCheckTask] [] - unexpected check error catalog.database.table
java.lang.NullPointerException: null


2023-04-20 13:47:21,977 ERROR [Metastore Scheduled Orphan Worker 1] [com.netease.arctic.ams.server.service.impl.OrphanFilesCleanService] [] - catalog.database.table orphan file clean unexpected error
java.lang.NullPointerException: null
        at com.netease.arctic.scan.TableEntriesScan.lambda$entries$0(TableEntriesScan.java:194) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at org.apache.iceberg.io.CloseableIterable$7$1.next(CloseableIterable.java:202) ~[iceberg-api-1.1.0.jar:?]
        at org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:65) ~[iceberg-api-1.1.0.jar:?]
        at org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:49) ~[iceberg-api-1.1.0.jar:?]
        at com.netease.arctic.ams.server.utils.UnKeyedTableUtil.getAllContentFilePath(UnKeyedTableUtil.java:58) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.OrphanFilesCleanService.getValidContentFiles(OrphanFilesCleanService.java:321) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.OrphanFilesCleanService.cleanContentFiles(OrphanFilesCleanService.java:128) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.OrphanFilesCleanService$TableOrphanFileClean.run(OrphanFilesCleanService.java:114) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
Are tables created via iceberg 0.13.0 version?

**Comment by zhongqishang** [comment]
> Are tables created via iceberg 0.13.0 version?

Table created by iceberg-flink-runtime-1.14-1.0.0

**Comment by shidayang** [comment]
I also had encountered this error. This seems to be caused by the lack of sequence in the entry of the delete file

**Comment by hellojinsilei** [comment]
After checking, I find that this is because in the iceberg 1.x version, the value of pos 2 in MetaData is `dataSequenceNumber`, while in the 0.x version, the value of pos 2 in the MetaData is `sequenceNumber`. For `dataSequenceNumber` we get the value is null, so throw the NPE.
Related code:
Iceberg 0.12.1 GenericManifestEntry.class
![image](https://user-images.githubusercontent.com/52364847/233837669-f51c54cc-ef07-4434-9871-ac9ab3ffef2f.png)

Iceberg 1.x GenericManifestEntry.class
![image](https://user-images.githubusercontent.com/52364847/233837689-3f8e1893-8fa8-41c0-a3f2-4d9abf21f2ec.png)

Arctic 0.4.x TableEntriesScan.class
![image](https://user-images.githubusercontent.com/52364847/233837816-9e7a9d43-7240-4f41-9ad9-b3daafc244ef.png)

**Comment by Aireed** [comment]
i think we should resolve the issue in  0.5.0. @baiyangtx @hellojinsilei .

**Comment by baiyangtx** [comment]
> i think we should resolve the issue in 0.5.0. @baiyangtx @hellojinsilei .

This is a critical bug. We will fix it as soon as posible.

**Comment by wangtaohz** [comment]
The logic that Iceberg scan entries changed in 1.1.0, but this only affect the `DELETED` entry, we can avoid this problem by not scanning `DELETED` entries, since the `DELETED` entries are not actually used. And, we can simply modify the code like this, 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/103108928/233940076-e04878d2-b288-4010-b940-acc7bba43dc3.png">

**Comment by wangtaohz** [comment]
> What if iceberg changed it's action in the feature, are there some others way to handle this problem?

I haven't dig deep into this problem, the related code is here, we can check it together.

`org.apache.iceberg.InheritableMetadataFactory.BaseInheritableMetadata#apply`

``` 
   public <F extends ContentFile<F>> ManifestEntry<F> apply(ManifestEntry<F> manifestEntry) {
      if (manifestEntry.file() instanceof BaseFile) {
        BaseFile<?> file = (BaseFile<?>) manifestEntry.file();
        file.setSpecId(specId);
      }

      if (manifestEntry.snapshotId() == null) {
        manifestEntry.setSnapshotId(snapshotId);
      }

      // in v1 tables, the data sequence number is not persisted and can be safely defaulted to 0
      // in v2 tables, the data sequence number should be inherited iff the entry status is ADDED
      if (manifestEntry.dataSequenceNumber() == null
          && (sequenceNumber == 0 || manifestEntry.status() == ManifestEntry.Status.ADDED)) {
        manifestEntry.setDataSequenceNumber(sequenceNumber);
      }

      if (manifestEntry.sequenceNumber() == null) {
        manifestEntry.setSequenceNumber(sequenceNumber);
      }

      // in v1 tables, the file sequence number is not persisted and can be safely defaulted to 0
      // in v2 tables, the file sequence number should be inherited iff the entry status is ADDED
      if (manifestEntry.fileSequenceNumber() == null
          && (sequenceNumber == 0 || manifestEntry.status() == ManifestEntry.Status.ADDED)) {
        manifestEntry.setFileSequenceNumber(sequenceNumber);
      }

      return manifestEntry;
    }
  }


```

**Comment by wangtaohz** [comment]
I think I understand why Iceberg's `BaseInheritableMetadata` handles things this way: 
- only the sequence number of the ADDED entry is supposed to be inherited from the manifest file
- while the sequence number of the DELETED entry can't be inherited and may be null
- and the sequence number of the EXISTING entry can't be inherited but is not supposed to be null.


We have two options to solve this problem:


-Option 1: 
If `TableEntriesScan` is designed to retrieve all entries (ADDED, DELETED, and EXISTING), we should accept the possibility that the sequence number may be null and change `long sequenceNumber` to `Long sequenceNumber` in `IcebergFileEntry`.


-Option 2: 
If `TableEntriesScan` is designed to retrieve the sequence number of alive entries only (ADDED and EXISTING), we should remove `aliveEntry` from `TableEntriesScan` and always ignore the DELETED entries.


Although we're currently using `TableEntriesScan` like Option 2, I still prefer Option 1. What do you think, [@zhoujinsong](https://github.com/zhoujinsong) [@baiyangtx](https://github.com/baiyangtx)?

**Comment by baiyangtx** [comment]
> I think I understand why Iceberg's `BaseInheritableMetadata` handles things this way:
> 
> * only the sequence number of the ADDED entry is supposed to be inherited from the manifest file
> * while the sequence number of the DELETED entry can't be inherited and may be null
> * and the sequence number of the EXISTING entry can't be inherited but is not supposed to be null.
> 
> We have two options to solve this problem:
> 
> -Option 1: If `TableEntriesScan` is designed to retrieve all entries (ADDED, DELETED, and EXISTING), we should accept the possibility that the sequence number may be null and change `long sequenceNumber` to `Long sequenceNumber` in `IcebergFileEntry`.
> 
> -Option 2: If `TableEntriesScan` is designed to retrieve the sequence number of alive entries only (ADDED and EXISTING), we should remove `aliveEntry` from `TableEntriesScan` and always ignore the DELETED entries.
> 
> Although we're currently using `TableEntriesScan` like Option 2, I still prefer Option 1. What do you think, [@zhoujinsong](https://github.com/zhoujinsong) [@baiyangtx](https://github.com/baiyangtx)?

I prefer option 1. This is an EntriesScan, and we return the stream of entries as same as iceberg mainfests keep is fine.

**Comment by wangtaohz** [comment]
> while the sequence number of the DELETED entry can't be inherited and may be null

Null value only occurs in this case: scan old iceberg table ( < 1.0.0) with iceberg 1.0.0+.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/103108928/234180652-19f4f211-95de-4560-bc4b-e8957fc8d587.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/103108928/234180760-1cd2b731-59a2-4ac7-85be-d3a810729c46.png">
