### ISSUE TITLE
[Feature]: Support Spark 3.2

### ISSUE THREAD

**Issue by Kyofin** [NetEase/arctic#1383]
### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
Thanks for your issue!

We have support the Spark 3.3 version in master branch and will release this feaure in 0.5.0, and for some situation the Iceberg spark connector may match the requirement.

Can you describe your usage scenario?
