### ISSUE TITLE
[Bug]: The column ‘_transaction_id’ and '_change_action' will be null when querying change table with spark

### ISSUE THREAD

**Issue by shidayang** [NetEase/arctic#1385]
### What happened?

The column ‘_transaction_id’ and '_change_action' will be null when querying change table

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

Spark

### How to reproduce

Using spark to query change table with ‘_transaction_id’  '_change_action' columns. 
such as:
`select _transaction_id, _change_action from {tableName}.change`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Affecting user workflow, classified as critical.

**Comment by shidayang** [comment]
> Affecting user workflow, classified as critical.

@baiyangtx want to change the implementation of ChangeTable#newChangeScan, and let ChangeTable directly rewrite the newScan method of Table, like this
```
public interface ChangeTable extends UnkeyedTable {

  TableScan newScan();
}
  public static class ChangeInternalTable extends BasicUnkeyedTable implements ChangeTable {

    public ChangeInternalTable(
        TableIdentifier tableIdentifier, Table changeIcebergTable, ArcticFileIO arcticFileIO,
        AmsClient client, Map<String, String> catalogProperties) {
      super(tableIdentifier, changeIcebergTable, arcticFileIO, client, catalogProperties);
    }

    @Override
    public TableScan newScan() {
      return new ChangeTableBasicIncrementalScan(this);
    }
  } 
```
so that this bug will naturally disappear after the modification.
