### ISSUE TITLE
[Improvement]: The execution time of delete table operation is too long

### ISSUE THREAD

**Issue by ShawHee** [NetEase/arctic#1394]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

After performing the drop table operation, if there are many hdfs files in the Arctic table, the file cleaning time will be very long, even up to 1-2 hours. If the user rebuilds the table during this process, the hdfs file of the new table may be cleaned up by the previous table deletion operation.

### How should we improve?

Optimize the operation of deleting tables.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@ShawHee Thanks for reporting this issue!
In order to better understand the issue you described, I have a few additional questions:

- How did you delete the table? Use `DROP TABLE` SQL in Spark?
- Do you mean that it takes 1-2 hours to execute the `DROP TABLE` SQL when there are too many files in the table?

**Comment by ShawHee** [comment]
- Yes, I use Use DROP TABLE SQL in Spark.
- It is a mixed-hive table upgraded from Hive.
- Yes. By observing the hdfs file, it can also be found that it takes a long time for the file to be deleted.

**Comment by zhoujinsong** [comment]
@ShawHee Thank you very much for taking the time to answer these questions！

AFAIK, It does take a lot of time to delete data files one by one from HDFS.
Perhaps we can refer to the approach of Hive or Spark to see if there is any way to speed up the processing time of this step.

How do you think? @baiyangtx
