### ISSUE TITLE
[Subtask]: Support Query on BaseStore for Trino engine

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/arctic#1407]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Parent issue

https://github.com/NetEase/arctic/issues/1304

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
AFAIK, Trino had supported scan on BaseStore.
reference:https://arctic.netease.com/ch/mpp/trino/#basestore
