### ISSUE TITLE
[Feature]: Increase support for Flink 1.13

### ISSUE THREAD

**Issue by JinsYin** [NetEase/arctic#1419]
### Description

Request to increase support for Flink 1.13, because most [Flink CDCs](https://github.com/ververica/flink-cdc-connectors/blob/release-2.2.1/pom.xml#L76) use version 1.13. 
In addition, some integration frameworks such as [Apache seatunel](https://github.com/apache/incubator-seatunnel/blob/dev/pom.xml#LL74C60-L74C60) and [Apache inlong](https://github.com/apache/inlong/blob/master/pom.xml#L155) are also using Flink version 1.13.

Due to not supporting version 1.13, the usage range of Arctic will be reduced.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@JinsYin Thanks for bringing this topic up!

However, before confirming the requirement, I would like to know what Table format users you are currently using. Iceberg format or Arctic Mixed format?

If you are using or able to use the Arctic Mixed format, the version supported by the Arctic Flink connector will indeed have an impact on you.

But if you want to use Iceberg Format only, you can use the Iceberg Flink connector directly, which makes the Flink version supported by the Arctic connector will not have any impact on you temporarily.

**Comment by JinsYin** [comment]
@zhoujinsong Thanks for your reply. 
I am using the Arctic Mixed format and using Minio as data storage. But when I used Apache Inlong and Apache Seatunel to write MySQL bin log data to Arctic lakehouse, I encountered a lot of trouble.

**Comment by zhoujinsong** [comment]
Flink 1.13 is published in 2021.
I still doubt the necessity of supporting such an old version.

I try to search the Flink version supported by Apache Seatunnel and Apache Inlong and find these:

- Apache Seatunnel seems to support Flink version > 1.12: https://seatunnel.apache.org/docs/start-v2/locally/quick-start-flink/
- Apache InLong is prepared to support more Flink versions: https://github.com/apache/inlong/issues/7260

Maybe we can try to find other ways to use the Arctic in Apache Seatunnl and Apache Inlong together first.
