### ISSUE TITLE
[Bug]: Unexpected data in Operations section of table details

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1453]
### What happened?

![image](https://github.com/NetEase/arctic/assets/109209550/39a31938-3c22-45fe-939a-73ae5b2ff304)
As shown in the figure, without performing any operation on the table, it can be seen that these Properties are repeatedly submitted in the Operation page, with repeated SET and UNSET operations.

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

1.Configure the following parameters on the Catalog configuration page
![image](https://github.com/NetEase/arctic/assets/109209550/326748a6-24f0-413f-b772-ce82a718dd74)
2. Create a new Arctic table, enable self-optimizing, and write data through Flink

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Display issues affect user experience, so I have classified it as major.
