### ISSUE TITLE
[Bug]: Unable to read data written from Log Store to File Store, when more than 1 parallel

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1455]
### What happened?

![image](https://github.com/NetEase/arctic/assets/109209550/182f7d7f-053d-40c9-8f7a-8912bcb39f36)
When I open the parallelism to 3, I cannot trigger the check point and write the data to the file store of the target table.
But when I change it back to 1, the job works fine.

### Affects Versions

0.4.x

### How to reproduce

1.Construct the following flink sql and set the number of parallelism to 3
2.Start the flink job

### Anything else

SQL as follows
CREATE CATALOG `arctic_test` WITH (
 'type' = 'arctic',
 'metastore.url' = 'thrift://xxxx:xxxxx/arctic_test'
);
CREATE TABLE source_table(
time TIMESTAMP(3),
WATERMARK FOR time AS time
) LIKE `arctic_test`.`arctic_test`.`arctic_test`;
INSERT INTO `arctic_test`.`arctic_test`.`arctic_test`/*+ OPTIONS('arctic.emit.mode' = 'auto', 'arctic.emit.auto-write-to-logstore.watermark-gap' = '5s', 'metrics.event-latency.enabled' = 'true', 'metrics.enabled' = 'true') */ 
SELECT 
xxxxxxx
 FROM source_table/*+ OPTIONS('properties.group.id' = 'xxxxxx', 'scan.startup.mode' = 'timestamp', 'scan.startup.timestamp-millis' = '1684643919991', 'log-store.enabled' = 'true', 'log-store.consistency-guarantee.enabled' = 'true', 'properties.bootstrap.servers' = 'xxxxxxx', 'format' = 'json', 'topic' = 'xxxxxxx', 'properties.key.serializer' = 'org.apache.kafka.common.serialization.ByteArraySerializer', 'properties.value.serializer' = 'org.apache.kafka.common.serialization.ByteArraySerializer', 'properties.key.deserializer' = 'org.apache.kafka.common.serialization.ByteArrayDeserializer', 'properties.value.deserializer' = 'org.apache.kafka.common.serialization.ByteArrayDeserializer', 'arctic.read.mode' = 'log') */

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YesOrNo828** [comment]
What is the partition number of the logstore topic of this table:`arctic_test.arctic_test.arctic_test` @shendanfengg

**Comment by shendanfengg** [comment]
A table with primary key and no partition

**Comment by shendanfengg** [comment]
And topic's partition is 1

**Comment by zhoujinsong** [comment]
The bug limits the concurrency setting of user tasks, so I have classified it as critical.

**Comment by YesOrNo828** [comment]
Flink 1.14 has resolved this case by [it](https://issues.apache.org/jira/browse/FLINK-2491):
when the source's parallelism exceeds your logstore topic partitions number, some tasks will show completion because it doesn't have the data, which would abort a checkpoint.

And also, I checked the below codes, and it's runnable in the flink-1.14:
```sql

create catalog arctic with (
    'type'='arctic',
    'metastore.url'='thrift://...'
    );
create table datagen(
    s_w_id int
) with (
    'connector'='datagen'
, 'rows-per-second'='1'
);
insert into arctic.flink_test.logs/*+ OPTIONS('log-store.catch-up'='true') */ select * from datagen;

create table printSink(
    s_w_id int
) with (
    'connector'='print'
);

insert into printSink select * from arctic.flink_test.logs/*+ OPTIONS('arctic.read.mode'='log','log-store.consistency-guarantee.enabled' = 'true') */;
```

So I will suggest:
- Change the flink1.12 source parallelism to less than or equal to the topic's partitions number.
- Upgrade to the flink1.14 version or a lager version.

**Comment by YesOrNo828** [comment]
@shendanfengg Another method to avoid this scenario:

Add auto-discover new topic partitions policy to LogStore Source. `'scan.topic-partition-discovery.interval'='1000'`.

For example:
```sql
select * from arctic.flink_test.local_logstore 
/*+ OPTIONS(
 'arctic.read.mode'='log',
 'scan.topic-partition-discovery.interval'='1000',
 'scan.startup.mode'='earliest') */
```
