### ISSUE TITLE
[Bug]: For mix-hive tables, data overwritten by Spark InsertOverwrite can still be queried with Hive after a period of time. 

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#1456]
### What happened?

For mix-hive tables, data overwritten by Spark InsertOverwrite can still be queried with Hive after a period of time. 
It was caused by the AMS compensation logic for committing Iceberg and Hive tables, which did not handle the scenario of partition deletion properly. The following is the code: 
![image](https://github.com/NetEase/arctic/assets/52364847/ab3b95e6-e79d-4737-9745-76b6f5dd42b2)

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

Spark

### How to reproduce

1. set spark.sql.sources.partitionOverwriteMode=static;
2. create table test1 (
    id int,
    name string,
    day string) using arctic partitioned by(day) tblproperties (
    "write.upsert.enabled"="true",
  "base.file-index.hash-bucket"="4"
);
3. insert into test1 values (1,'a','a');
4. create table test2 (
    id int,
    name string,
    day string) using arctic partitioned by(day) tblproperties (
    "write.upsert.enabled"="true",
  "base.file-index.hash-bucket"="4"
);
5.  insert into test1 partition (day='a') select id,name from test2;
6. Restart AMS
7. use hive execute : select * from test1;

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Does this issue only affect the 0.3.x branch, or does it still exist in 0.4.x/master?

**Comment by zhoujinsong** [comment]
The bug will cause incorrect partition information on Hive, so I have classified it as critical.
