### ISSUE TITLE
[Bug]: table optimize history abnormal display

### ISSUE THREAD

**Issue by xujiangfeng001** [NetEase/arctic#1494]
### What happened?

When tableA is optimized, the optimized records of tableA can be viewed in the details interface (Optimized). When the user deletes tableA and creates a new tableA table with the same name, the optimized records of the original table will remain in the details interface (Optimized).

I think this is unreasonable. If a table with the same name is deleted and recreated, it may only have the same table name and may not necessarily be associated. Therefore, I believe that when a table is deleted, the corresponding optimize record should also be deleted to avoid such a situation.

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

AMS

### How to reproduce

Repeat the steps as follows:

1. Create a table named tableA, optimize it, and generate optimize records
2. Delete tableA and create a table with the same name, tableA, to view the optimize record

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
Thanks for you report. This problem may also exist in 0.5.0.

**Comment by shidayang** [comment]
This problem in 0.5.0 may be because OptimizingMapper#selectSuccessOptimizingProcesses method is querying through catalog.db.table instead of tableId

**Comment by xujiangfeng001** [comment]
Hi @shidayang thank you very much for your reply. I will confirm this issue as soon as possible and fix it. You can assign tasks to me.

**Comment by shidayang** [comment]
> Hi @shidayang thank you very much for your reply. I will confirm this issue as soon as possible and fix it. You can assign tasks to me.

Ok, I had assigned it to you

**Comment by xujiangfeng001** [comment]
Hi @zhoujinsong ,after reviewing the code related to retrieving table lists in Arctic's 0.5.x version, I noticed that the frontend can obtain the `table ID` from the `table_identifier`. I have a question regarding the process of fetching detailed information about a table. Why do we still use the format `catalog.db.tableName` to request table details? In my opinion, we can simply use the `table ID` to request the detailed information of the table.

Therefore, regarding this issue, can I directly use the` table ID` to retrieve optimization information for the table, instead of performing a join between `table_identifier` and `table_optimizing_process` using `catalog.db.tableName`? Based on my testing, the `table_identifier` is also deleted when a table is deleted. Thus, I believe that the `table ID` in `table_identifier` is reliable.

I'm looking forward to your response.

**Comment by zhoujinsong** [comment]
> Why do we still use the format catalog.db.tableName to request table details?

In my opinion, `table ID` is an internal concept of the system and may not be easy to understand for external users. Although it can be used normally in communication with the front-end, if the HTTP interface is later opened as an OPEN API, the parameter format will become less user-friendly.

> Can I directly use the table ID to retrieve optimization information for the table, instead of performing a join between table_identifier and table_optimizing_process using catalog.db.tableName?

Yes, Performing a join between `table_identifier` and `table_optimizing_process` is just a way to find the `table_id` from `table_identifier` if we keep the request parameter to be `table_identifier`.

In addition, if a table is deleted, it will indeed be removed from the `table_identifier`, but some of its optimizing histories will not be immediately deleted. One reason for adding `table_id` is to distinguish new tables with the same name in this situation.

**Comment by xujiangfeng001** [comment]
> > Why do we still use the format catalog.db.tableName to request table details?
> 
> In my opinion, `table ID` is an internal concept of the system and may not be easy to understand for external users. Although it can be used normally in communication with the front-end, if the HTTP interface is later opened as an OPEN API, the parameter format will become less user-friendly.
> 
> > Can I directly use the table ID to retrieve optimization information for the table, instead of performing a join between table_identifier and table_optimizing_process using catalog.db.tableName?
> 
> Yes, Performing a join between `table_identifier` and `table_optimizing_process` is just a way to find the `table_id` from `table_identifier` if we keep the request parameter to be `table_identifier`.
> 
> In addition, if a table is deleted, it will indeed be removed from the `table_identifier`, but some of its optimizing histories will not be immediately deleted. One reason for adding `table_id` is to distinguish new tables with the same name in this situation.

Thank you very much for your reply. I will solve this issue as soon as possible based on this idea.
