### ISSUE TITLE
[Bug]: The error log for starting the local optimizer process was not printed

### ISSUE THREAD

**Issue by shidayang** [NetEase/arctic#1522]
### What happened?

I found the error message of starting local optimizer was not printed。

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

If you try to start the LocalOptimizer service when you don't have the permission to run localOptimize.sh, you may notice that there is no error log and the optimizer cannot start properly.

### Anything else

The reason for this is that the status and error message of the process returned by the runtime.exec() method were not handled properly.
![image](https://github.com/NetEase/arctic/assets/26699250/484064fc-53e6-41d1-8a85-c26af536489e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhongqishang** [comment]
I think it's not only for local optimizer, same for flink optimizer. @shidayang @xujiangfeng001

**Comment by shidayang** [comment]
> I think it's not only for local optimizer, same for flink optimizer. @shidayang @xujiangfeng001

I agree with you. Could you also fix for flink optimizer
