### ISSUE TITLE
[Improvement]: Improve the response speed of the getOptimizeInfo method

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#1526]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Use `getAs` method in loop, `getAs` is a jdbc access operation that is a heavy operation.

com.netease.arctic.server.dashboard.ServerTableDescriptor#getOptimizeInfo

```
tableOptimizingProcesses.stream().map(e -> {
      OptimizedRecord record = new OptimizedRecord();
      List<TaskRuntime> taskRuntimes = getAs(
          OptimizingMapper.class,
          mapper -> mapper.selectTaskRuntimes(e.getTableId(), e.getProcessId())).stream()
          .filter(taskRuntime -> TaskRuntime.Status.SUCCESS.equals(taskRuntime.getStatus()))
          .collect(Collectors.toList());
      ...
      return record;
    }).collect(Collectors.toList())
```

### How should we improve?

Not use jdbc connection in the loop, Use `MetricsSummary` from `TableOptimizingProcess`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
I think it would be better to use SQL join in this scenario
