### ISSUE TITLE
[Feature]: add self-optimize  detail in optimized tab of table 

### ISSUE THREAD

**Issue by Aireed** [NetEase/arctic#1535]
### Description

1、add detailed display on the optimized tab page, each record can be clicked to expand details. The details include various types of files involved in merging (insert/eq-delete/pos-delete/base), execution results (including exception information when execution fails), involved partition list, snapshot information, summary information, etc.
2、optional, we can  filter rows  by partition.

### Use case/motivation

1、Use these metrics to help users locate issues.
2、get the detail of the self-optimizing record

### Describe the solution

1、front end  add detail  info  after we click the  self-optimizing record.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
The contents for an Optimizing Process should contains:

The information displayed in the list:

```
 - Start Time: 2023-06-06 12:00:00
 - Optimize Type: Minor/Major/Full
 - Status: Running/Closed/Success/Failed
 - Duration: 20s
 - Progress: 0-100%
 - Finish Time: commit time when success or failed time when failed
 - Input:
   - Count:
   - Size:
 - Output:
   - Count:
   - Size:
```

More detailed information:

```
Overview:
 - Process Id: 1002
 - Success Task Count:
 - Total Task Count:
 - Plan Cost: 253ms
 - Fail Reason: a long String or null
 - Affected Partitions: a list of partitions
 - Current Snapshot Id:
 - Current ChangeStore Snapshot Id: may be null
 - From Sequence: A map with partition as key and long as value
 - To Sequnece: A map with partition as key and long as value


File Statistics:
 - Input:
   - Count:
   - Size:
   - Rewrite Data Files
     - Count:
     - Size:
   - Rewrite Pos-Delete Data Files
     - Count:
     - Size:
   - Pos-Delete Files
     - Count:
     - Size:
   - Read-Only Pos-Delete Files:
     - Count:
     - Size:
   - Equ-Delete Files
     - Count:
     - Size:

 - Output:
   - Count:
   - Size:
   - Data Files:
    - Count:
    - Size:
   - Delete Files:
    - Count:
    - Size:


Tasks:
 - Total Count:
 - PLANNED Count:
 - SCHEDULED Count:
 - ACKED Count:
 - FAILED Count:
 - SUCCESS Count:
 - CANCELED Count:
 - Max Retry:
 - Max Cost Time:
 - Min Cost Time:
 - Average Cost Time:


Commit Result:
 - Snapshot(may contains 1 or 2 snapshots)
  - snapshot-id:
  - sequence-number:
  - parent-snapshot-id:
  - timestamp-ms:
  - summary: a map of key value
```

**Comment by wangtaohz** [comment]
A Diagram of the list
<img width="850" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/624e75bf-42c8-4911-9859-9c7770f50c34">

**Comment by zhongqishang** [comment]
@wangtaohz Process can be like spark, 78/544 (11 running), what do you think?

**Comment by wangtaohz** [comment]
After changing the `Process`.
<img width="848" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/d3b27050-db10-4085-86e8-96b1f01e6e5a">

**Comment by wangtaohz** [comment]
Modify the File Statistics:

```
File Statistics:
 - Input:
   - Count:
   - Size:
   - Data Files:
     - Rewrite (count/size)
     - Read-only (count/size)
   - Pos-Delete Files
     - Rewrite (count/size)
     - Read-only (count/size)
   - Equ-Delete Files
     - Rewrite (count/size)
     - Read-only (count/size)

 - Output:
   - Count:
   - Size:
   - Data Files (count/size):
   - Pos-Delete Files (count/size):
   - Equ-Delete Files (count/size)

```

**Comment by wangtaohz** [comment]
A Diagram of Detail
all the File Statistics will be displayed in the `Metrics`
<img width="928" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/9fc7afb5-02d8-456e-b551-6cd37b21badb">
