### ISSUE TITLE
[Bug]: Table refresh not get newly config

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#1539]
### What happened?

A table with optimization disabled via `'self-optimizing.enabled'='false'` did not trigger the optimizer after resetting `'self-optimizing.enabled'='true'`

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Start AMS
2. Via `ALTER TABLE` set `'self-optimizing.enabled'='false'`
3. Set `'self-optimizing.enabled'='true'` after the table have a new snapshot

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
I will follow this issue. I have encountered the same problem and fixed it, I will try to reproduce it.
