### ISSUE TITLE
[Bug]: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;

### ISSUE THREAD

**Issue by hhw3KevinHou** [NetEase/arctic#1575]
### What happened?

After run "mvn -DskipTests package -P toolchain"
I can not build as the output: 
![image](https://github.com/NetEase/arctic/assets/14155363/06d2b24b-f83f-4ccc-a2d1-f1cefb6cc886)

Maybe the reason is version confilict:
![image](https://github.com/NetEase/arctic/assets/14155363/4481d56b-572c-4cf1-82f1-56a7f541c63c)

Where am I wrong？

### Affects Versions

0.4.1

**Comment by baiyangtx** [comment]
We have removed module spark 2.3 in version 0.5.0, the current master branch doesn't contain this module.

So if you don't need the Spark 2.3 module, you can remove it from the pom.xml and try building again.

**Comment by hhw3KevinHou** [comment]
Same error of spark3.1 after removed spark2.3.
![image](https://github.com/NetEase/arctic/assets/14155363/77bbeced-439d-468d-9524-657cfa77784e)

**Comment by baiyangtx** [comment]
What's your maven version? 
I found some similar issues.   

https://www.mail-archive.com/issues@spark.apache.org/msg307469.html
https://blog.csdn.net/u013086392/article/details/124164269

It seems to be a compatibility issue between a higher version of Maven and a lower version of the `scala-maven-plugin`. Could you try changing the version of the scala-maven-plugin in the pom.xml to 4.8.1?

**Comment by hhw3KevinHou** [comment]
![image](https://github.com/NetEase/arctic/assets/14155363/96c3469e-a8bf-4287-bc46-ceec725d99ef)

**Comment by hhw3KevinHou** [comment]
It works after set 4.8.1.    
And I inserted :
![image](https://github.com/NetEase/arctic/assets/14155363/1c27fa3b-9bce-4066-a55b-3f13405a42ff)

Finally:
![image](https://github.com/NetEase/arctic/assets/14155363/c3e5cadf-8efe-4020-ad17-903825004f20)



BTW, it better to use MVNW  to fix Maven version:
![image](https://github.com/NetEase/arctic/assets/14155363/f600f079-cea3-42f3-8f97-5924b11946d1)

**Comment by baiyangtx** [comment]
Great, this is the first time I've encountered this issue too. Upgrading the scala-maven-plugin version seems like a pretty good solution. Would you be willing to submit a PR to fix this issue? It could help other people who encounter similar problems.
