### ISSUE TITLE
[Bug]: When the partition field is null, the optimizer is always in a failure loop

### ISSUE THREAD

**Issue by XiaoGerGer** [NetEase/arctic#1600]
### What happened?

If you insert a record with a null partition field and it looks like `/arctic-warehouse/my-catalog/ods.db/table-name/ds_day=null` in hdfs, the Optimizer will encounter an error. And record `fail_reason` is `Text 'null' could not be parsed at index 0` in the table_optimizing_process table, and continue to try to optimize the table, and then in a failed loop, Other tables fail to line up

![image](https://github.com/NetEase/arctic/assets/20039124/110759b3-727c-4243-9a8b-a7b190d9b919)
![image](https://github.com/NetEase/arctic/assets/20039124/fdb3162f-ab69-42ee-b3fe-60bff90f5999)

### Affects Versions

master-0.5.0

### What engines are you seeing the problem on?

Optimizer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
Thank you for reporting this bug. Which format are you using? Mixed-format or Iceberg-format?

**Comment by zhoujinsong** [comment]
> Thank you for reporting this bug. Which format are you using? Mixed-format or Iceberg-format?

To my knowledge, the format used is mixed-iceberg format, but I think iceberg format may also have similar issues.

**Comment by XiaoGerGer** [comment]
> Thank you for reporting this bug. Which format are you using? Mixed-format or Iceberg-format?

mixed-iceberg format

**Comment by shidayang** [comment]
I constructed a Mixed-iceberg table and inserted data with a null partition field, but I was unable to reproduce this issue. 
<img width="822" alt="image" src="https://github.com/NetEase/arctic/assets/26699250/56554a37-68dc-487d-97a6-126d88351a7e">
<img width="1164" alt="image" src="https://github.com/NetEase/arctic/assets/26699250/6482a9e8-3e05-4bb6-a9f2-51639fffb5ef">
Does this need to be triggered under certain specific circumstances? Can you provide more details?
