### ISSUE TITLE
[Bug]: when partition value contains spaces, optimize can't process correctly

### ISSUE THREAD

**Issue by Aireed** [NetEase/arctic#1653]
### What happened?

1、When the partition value contains spaces, arctic writer will replace the spaces with + when creating a directory.

2、optimize will process the same file repeatly.

### Affects Versions

0.3.1/0.4.2/master

### What engines are you seeing the problem on?

Optimizer

### How to reproduce

Insert a record with a partition value containing spaces into a table.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
Reproduce
1. create table
```
CREATE TABLE IF NOT EXISTS db.user3 (
    id INT,
    name string,
    city string,
    PRIMARY KEY(id)
) USING arctic 
PARTITIONED BY (identity(city));
```

2. insert data
```
insert into db.user3 values (106, "ggg","Hang Zhou");
```
<img width="952" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/0cafeddb-0c71-461c-9047-c35fef66c9ac">


3. wait for optimizing, then 
```
select * from db.user3;
```
<img width="1162" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/2dd800d3-5830-4dab-bc88-ac7b73786f7d">
