### ISSUE TITLE
[Bug]: The file count/size and quota occupation are `0` when optimizing status is pending

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#1691]
### What happened?

The file count and size should not be `0` when table is in pending status
<img width="1414" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/44fe8d3e-e3b1-4dab-9c85-7e348a89d85c">

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. create an table
2. not start any optimizer
3. insert some record into the table
4. wait for 1min, the table's optimizing status will be pending, and the file count and file size are `0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XBaith** [comment]
I use to think that's a new feature, haha
