### ISSUE TITLE
[Bug]: there are some empty commit

### ISSUE THREAD

**Issue by Aireed** [NetEase/arctic#1698]
### What happened?

there are some empty commit when no data input
![image](https://github.com/NetEase/arctic/assets/8862395/42d693db-ea12-4aec-93a1-3a59b88f4c9f)

### Affects Versions

master

### What engines are you seeing the problem on?

Optimizer

### How to reproduce

table:   mixed hive table, with primary key , no partition key
data:  insert data from a flink datagen source.
optimizer:  Flink optimizer

After stopping the upstream source for more than a day, it was discovered that there were some empty commits.

**I'm not sure if I can reproduce it reliably.**

![image](https://github.com/NetEase/arctic/assets/8862395/9337a3f9-3fc5-435b-a48e-c154762ce01d)

![image](https://github.com/NetEase/arctic/assets/8862395/9741dccf-879f-4fc4-864c-d93534ccfd51)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
They are some empty delete operations on the Change Store.

Executed once per hour, it appears to behave like `expire-snapshots` based on the execution interval.

**Comment by wangtaohz** [comment]
I have reproduced the issue and it is indeed a bug.

It happens when deleting ttl change files in `expire-snapshots` executor,  and it repeatedly deletes the same files multiple times which generates an empty snapshot except for the first time.

**Comment by HuangFru** [comment]
Expire executor gets the latest expired snapshot and plans it to get data files to delete, this makes it always have fake data files(deleted by the first time) to delete, so it will repeatedly delete some data files, This is a bug, I'll fix it.
