### ISSUE TITLE
[Bug]: Ams initialization exception due to hadoop-client conflict

### ISSUE THREAD

**Issue by huyuanfeng2018** [NetEase/arctic#1704]
### What happened?

![image](https://github.com/NetEase/arctic/assets/40817998/8539e232-9541-4e75-aec6-c9818fdcf317)
Initialization exception due to version conflict

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
Thank you for reporting this bug.
