### ISSUE TITLE
[Improvement]: Make the Thrift client pool's size adapt to optimizer concurrency

### ISSUE THREAD

**Issue by HuangFru** [NetEase/arctic#1707]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the max size of the Thrift client pool for optimizer is fixed to 5:
<img width="818" alt="截屏2023-07-17 14 59 05" src="https://github.com/NetEase/arctic/assets/68625618/694bfa0a-70f1-4561-9041-bec841d31a6b">
If the concurrency of the optimizer is greater than 5 and the poll task cost plenty of time(such as plan), tasks that have been polled may not be able to finish the ack and complete operations. Because the thread pool is likely to be full of poll task threads, one is planning and the others are waiting for lock.
So the max size of the pool is better to adapt with the optimizer concurrency.

### How should we improve?

Make the Thrift client pool's size adapt to optimizer concurrency.
If scale out an optimizer with a concurrency of 10, the max size of the client pool should be 10.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
It seems that the connection for the optimizer touche the AMS should not be restricted by the connection pool. On the other hand, the requests for optimizer poll/ack/complete should also not be limited by the connection pool. Can we simply set the maximum connection limit of the connection pool to `Integer.MAX_VALUE`? The maximum number of connections held by optimizer at the same time is equal to its concurrency + 1, so this setting is relatively safe.

**Comment by HuangFru** [comment]
I think it's doable. And I notice that the `CLIENT_POOL_MAX` is set to the max idle:
<img width="893" alt="image" src="https://github.com/NetEase/arctic/assets/68625618/42c82b0b-3d6b-428c-80ef-ec5b7880ed0a">
The min and max number of idle objects can remain the same as before.
The real impact should be the max number of total:
<img width="617" alt="image" src="https://github.com/NetEase/arctic/assets/68625618/66e24140-fb4b-482a-8305-f30256be084a">
The default value is 8 and we can set it to a negative number which means no limit.
<img width="701" alt="image" src="https://github.com/NetEase/arctic/assets/68625618/f63a2db9-836a-4a5c-8c5c-1101e018f0fd">

**Comment by zhoujinsong** [comment]
> doable

Yes, can you fix this issue according to the result of our discussion?

**Comment by HuangFru** [comment]
> Yes, can you fix this issue according to the result of our discussion?

No problem.
