### ISSUE TITLE
[Improvement]: The AMS API should shade the ZooKeeper and Curator packages to prevent potential issues caused by version incompatibility

### ISSUE THREAD

**Issue by hameizi** [NetEase/arctic#1710]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The AMS API should shade the ZooKeeper and Curator packages to prevent potential issues caused by version incompatibility, such as the following: 
![image](https://github.com/NetEase/arctic/assets/18445460/7d5c021f-72c6-458e-9071-d2be6b18b96f)

### How should we improve?

Shade the ZooKeeper and Curator packages in the AMS API module.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
It seems to be the same issue with #1611 .
@xieyi888 had tried to fix it by #1612.

Can you both review the solution approach and PR together? We can work together to push forward the resolution of this issue.

**Comment by hameizi** [comment]
> It seems to be the same issue with #1611 . @xieyi888 had tried to fix it by #1612.
> 
> Can you both review the solution approach and PR together? We can work together to push forward the resolution of this issue.

ok, i will close this PR, and this issue will be fixed in PR #1611 .

**Comment by xieyi888** [comment]
Thansk

> It seems to be the same issue with #1611 . @xieyi888 had tried to fix it by #1612.
> 
> Can you both review the solution approach and PR together? We can work together to push forward the resolution of this issue.

Thanks, I had change ams/api/pom.xml  in https://github.com/NetEase/arctic/pull/1612 ,Please take a look , Thanks so much
