### ISSUE TITLE
[Bug]: The "Files" tab & table info is lost when refresh the Tables > Transactions page.

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#1724]
### What happened?

![image](https://github.com/NetEase/arctic/assets/16421989/9482e5c1-d789-4bed-909b-7144a1f5a013)

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
It seems to be the table that encountered an error is an Iceberg Format table? Also, is this issue always reproducible?

**Comment by zhongqishang** [comment]
Yes, Iceberg Format table and always reproducible.

**Comment by zhoujinsong** [comment]
Then we should fix it before releasing v0.5.0 to help users get a better experience.
