### ISSUE TITLE
[AMS] Error when import ams_init.sql

### ISSUE THREAD

**Issue by mcruijie** [NetEase/arctic#206]
Error when import ams_init.sql into mysql
an end character ';' id missing at the end of the creating table snapshot_info_cache

**Comment by zhoujinsong** [comment]
hi, @mcruijie could you please descripe the error?
or the same error with #208?

**Comment by mcruijie** [comment]
> hi, @mcruijie could you please descripe the error? or the same error with #208?

the error description has been added and the error has been solved @zhoujinsong
