### ISSUE TITLE
[Improvement]: support long table_identifier

### ISSUE THREAD

**Issue by hameizi** [NetEase/arctic#254]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

support long table_identifier. now table_identifier support varchar(64), but in many scense there maybe longer table name. Refer to the hive metastore design, hive metastore support both table name and database name  varchar(128), our table_identifier contain catalog name, database name and table name, so we will support table_identifier varchar(384)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@hameizi   Could you please describe this issue in more detail？

**Comment by hameizi** [comment]
> @hameizi Could you please describe this issue in more detail？ For example, how many characters would the table identifier support?

@zhoujinsong update issue desc
