### ISSUE TITLE
start ams.sh failed on mac os, but arctic process is running normally.

### ISSUE THREAD

**Issue by JamesIsHuang** [NetEase/arctic#28]
start ams.sh failed on mac os, but arctic process is running normally.
![image](https://user-images.githubusercontent.com/12915720/180123525-44fa1bd6-20e0-48cb-bd94-e1123dcadb96.png)

**Comment by hameizi** [comment]
The server port(1260 and 1630) is occupied?

**Comment by JamesIsHuang** [comment]
> The server port(1260 and 1630) is occupied?

yeah

**Comment by zhoujinsong** [comment]
I got the same problem in my mac os enviroment and there is no error logs in app.log file.
![POPO20220722-143339](https://user-images.githubusercontent.com/7424437/180377925-5d0b73a3-4007-4b5d-8c3b-8b6a1c3fa680.jpg)

**Comment by zhoujinsong** [comment]
the `ams.sh stop` cannot work either, it seems the script got the run pid
<img width="523" alt="image" src="https://user-images.githubusercontent.com/7424437/180379286-895b71d7-3d88-46cf-9e30-559bff04bf39.png">

**Comment by hameizi** [comment]
@zhoujinsong @JamesIsHuang maybe you call `ams.sh start` repeatedly? And when you want restart ams you only called `ams.sh start` but not call stop?

**Comment by zhoujinsong** [comment]
> 

I don't think i call start repeatedly
