### ISSUE TITLE
[Bug]: insert overwirte partition table failed

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#334]
### What happened?

create table test_arctic_10 (id int , name string, dt string) using arctic partitioned by (dt);
insert overwrite test_arctic_10 values (1, 'aaa','1'), (2, 'bbb','2'), (3, 'ccc','1');
failed 
![image](https://user-images.githubusercontent.com/52364847/188622060-48c2d2cd-9f12-449b-a175-944191c4d5e1.png)

but  insert overwrite test_arctic_10 values (1, 'aaa','1'), (2, 'bbb','2'), (3, 'ccc','3');
it will success!

### Affects Versions

0.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shendanfengg** [comment]
Similarly, if there is no primary key and no partition table, an Insert over write will be written to multiple directories, resulting in data loss from Hive
