### ISSUE TITLE
[Improvement][Optimize]: check data consistency of optimize

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#336]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

There is no mechanism to guarantee data consistency after optimize.

### How should we improve?

before optimize commit, check file metrics before and after optimize

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hzluting** [comment]
I fixed it in #401
