### ISSUE TITLE
[Bug]: Parquet files written natively by hive may not be read by spark

### ISSUE THREAD

**Issue by HuangFru** [NetEase/arctic#348]
### What happened?

Parquet files written natively by hive may not be read by spark for 'nameMapping' field is null. But now it works fine, may occur in the future.

### Affects Versions

Release 0.3.1

### What engines are you seeing the problem on?

Spark

### How to reproduce

Read parquet files written natively by hive, then upgrade the table in AMS.Then read it  use spark may,
this situation may occur.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@HuangFru Could you please add some exception information to help other user search this bug?
