### ISSUE TITLE
[Improvement][OPTIMIZE]:Supports external system registration and management of Optimizer

### ISSUE THREAD

**Issue by hameizi** [NetEase/arctic#351]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

now external system can't  registration and management of Optimizer

### How should we improve?

1.Provides interfaces for registering and unregistering Optimizers
2.Provides an interface to get the optimize Group

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Aireed** [comment]
I think it's a good idea!   users who use arctic may have a real-time  platform,  optimize process may be managed by the platform for start/stop, alter.

**Comment by wangtaohz** [comment]
It seems to be a good proposal, but on what condations should we call the interface `Unregistering Optimizers`?

**Comment by hameizi** [comment]
> It seems to be a good proposal, but on what condations should we call the interface `Unregistering Optimizers`?

In my opinion when external system drop optimizer job(but not stop optimizer job, because optimizer job maybe restart in future) that we should call  `Unregistering Optimizers`.

**Comment by zhoujinsong** [comment]
@hameizi Thanks a lot for propose this improvement and I also think that we should support external system deploy optimizer. But in my opinion, I would do it like this:

- Start optimizer with a AMS url as argument
- Optimizer register itself after started
- Add an authentication mechanism if needed to help AMS validate this optimizer
- AMS handle optimizer's life cycle with heartbeat

**Comment by wangtaohz** [comment]
> @hameizi Thanks a lot for propose this improvement and I also think that we should support external system deploy optimizer. But in my opinion, I would do it like this:
> 
> * Start optimizer with a AMS url as argument
> * Optimizer register itself after started
> * Add an authentication mechanism if needed to help AMS validate this optimizer
> * AMS handle optimizer's life cycle with heartbeat

I support the design, and also, only registered optimizer could poll tasks.
