### ISSUE TITLE
[Bug][AMS]: Full optimize and Major Optimize support Hive only optimize some node rather than partition

### ISSUE THREAD

**Issue by hzluting** [NetEase/arctic#368]
### What happened?

Because will check some condition when collect tasks.
For not support hive optimize, it can skip some tasks reduce resource consumption.
But for support hive optimize, skip some node tasks will lead to some datas not in hive.

### Affects Versions

0.3.1

### How to reproduce

1.create a keyed unPartition table support hive
2.write data to all nodes
3.write some delete to some nodes but not all
4.after full optimize, hive can't query all data

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@hzluting  Dose this bug affect version 0.3.1 too?

**Comment by hzluting** [comment]
> @hzluting Dose this bug affect version 0.3.1 too?

no, only affect support hive, some node files don't move to hive location

**Comment by zhoujinsong** [comment]
> > @hzluting Dose this bug affect version 0.3.1 too?
> 
> no, only affect support hive, some node files don't move to hive location

But we support hive table since version 0.3.1 and We have not released 0.3.2

**Comment by hzluting** [comment]
> > > @hzluting Dose this bug affect version 0.3.1 too?
> > 
> > 
> > no, only affect support hive, some node files don't move to hive location
> 
> But we support hive table since version 0.3.1 and We have not released 0.3.2

I remember wrong.it will affect 0.3.1
