### ISSUE TITLE
[Bug]: Query for no data using left Join

### ISSUE THREAD

**Issue by wqxs** [NetEase/arctic#369]
### What happened?

I used Docker to install AMS，

Here is the SQL I executed in SQL Client

`CREATE CATALOG arctic WITH (
	'type' = 'arctic',
	'metastore.url'='thrift://127.0.0.1:1260/local_catalog'
);`

Create a class table
`CREATE TABLE arctic.test.class (
	id BIGINT,
	class_name STRING,
	PRIMARY KEY (id) NOT ENFORCED
);`
`insert into arctic.test.class values(1,'yiban');`
`insert into arctic.test.class values(2,'erban');`

Create the student table
`CREATE TABLE arctic.test.student (
	id BIGINT,
	name string,
	class_id BIGINT,
	PRIMARY KEY (id) NOT ENFORCED
);`
`insert into arctic.test.student values(1,'xiaoming',1);`
`insert into arctic.test.student values(2,'xiaoho',1);`
`insert into arctic.test.student values(3,'xiaozhang',2);`

join
`select class.class_name,count(student.id) from arctic.test.class class left join arctic.test.student student on class.id = student.class_id
group by class.class_name;
`

No data after execution
![image](https://user-images.githubusercontent.com/69672009/190385107-b5bbd086-a64e-40c1-a25d-8c98e616cc86.png)

### Affects Versions

v0.3.1-rc1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YesOrNo828** [comment]
@wqxs  Thanks for reporting this. Actually, we have addressed it with this patch(https://github.com/NetEase/arctic/pull/328). Maybe you can compile the master branch, `mvn clean package -DskipTests`
How to get the flink-runtime jar: https://arctic.netease.com/ch/flink/flink-get-started/#_1

**Comment by YesOrNo828** [comment]
Close it because this issue has been addressed.
