### ISSUE TITLE
[Feature]: Automatic toggle switch to enable double write

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/arctic#389]
### Description

As of now, we have to manually config the `arctic.emit.mode` to determine which stores the flink writers should emit data to before the job launch. There are three enums of the `arctic.emit.mode`: 'file', 'log', 'file,log'.

### Use case/motivation

Use case:
All changelog and historical data ingress into the arctic stores. Writing historical data into filestore and writing incremental data into logstore is expected.

### Describe the solution

Add a new enum to the `arctic.emit.mode`: 'auto'. It means that the flink job writes data into the filestore first, then writes data into the logstore and the filestore immediately after matching an appropriate pattern.
```
create source(
tm timestamp(3),
WATERMARK FOR tm AS tm ) with (...);

insert into arctic /* +OPTIONS ('arctic.emit.auto-write-to-logstore.watermark-gap'='10s')*/
from source;
```

| Config     | default  | type | Note                                     |
| --------- |------------|------------|------------------------------------------|
| arctic.emit.mode     | auto |String | file, log, auto. e.g. <br> 'file' means only writing data into filestore.  <br> 'log' means only writing data into logstore.  <br> 'file,log' means writing data into both filestore and logstore. <br> 'auto' means writing data into filestore if the logstore of the arctic table is disabled; Also means writing data into both filestore and logstore if the logstore of the arctic table is enabled. <br> 'auto' is recommended.                              |
| arctic.emit.auto-write-to-logstore.watermark-gap     | none |Duration | Only enabled when 'arctic.emit.mode'='auto', if the watermark of the arctic writers is greater than the current system timestamp subtracts the specific value, writers will also write data into the logstore.  Default: the logstore writer is enabled immediately once the job is launched. <br>This value must be greater than 0.                            |

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@YesOrNo828 Thanks for proposing this new feature. And I think it is an useful feature in ingestion situation too. But I still have some questions and suggestions about the solution:

- What's the behavior if setting `arctic.emit.mode=auto` without setting `auto.emit.pattern.watermark.comparison`? Should we change the default value of `arctic.emit.mode` to `auto` ?
- Does the Flink source table must have a watermark setting at your situation? What's the hehavior if it does not have?
- Does config name `arctic.emit.auto-write-to-changelog.watermark-lag` is more easy to understand ?

**Comment by zhoujinsong** [comment]
@YesOrNo828  Thanks for your replying.

**Comment by zhoujinsong** [comment]
Another question come to mind:

Would the job start to emit only to Filestore again after ingestion job restart. We can add a state to solve this problem of course. But what if we start this job without a save point?

**Comment by YesOrNo828** [comment]
Emit to Filestore and Logstore if table enable Logstore (Source table does not have a watermark setting or arctic.emit.auto-write-to-logstore.watermark-gap is not setted)

> 'arctic.emit.mode' = 'file,log', IMO, this configuration has the same meaning. This conflits with the previous approach.

Would the job start to emit only to Filestore again after ingestion job restart. We can add a state to solve this problem of course. But what if we start this job without a save point?

> Yes, if the flink job restarts without a checkpoint/savepoint after a long stop. It will lose its state. How about saving it in arctic metadata?

**Comment by zhoujinsong** [comment]
'arctic.emit.mode' = 'file,log', IMO, this configuration has the same meaning. This conflits with the previous approach.

> I'd like to change the default value of `arctic.emit.mode` to `auto` and make it proper in most situation so user DO  NOT need to config this property manually. And We sould emit to both Filestore and Logstore in most situation if table enable Logstore. Of course 'arctic.emit.mode' = 'file,log' has the same meaning in this situation.

How about saving it in arctic metadata?

> But It is a state only for this ingestion job, how should we identify different ingestion jobs ? Or should we suggest user remove the `arctic.emit.auto-write-to-logstore.watermark-gap` option when restart without a checkpoint/savepoint ？

**Comment by YesOrNo828** [comment]
After discussing offline with @zhoujinsong, we will save the flag whether the logstore data has caught up in the arctic table properties.
`log-store.catch-up` and `log-store.catch-up-timestamp`
