### ISSUE TITLE
[Bug]: Flink using a partitioned Arctic table for dimensional join would encounter ClassCastException

### ISSUE THREAD

**Issue by lklhdu** [NetEase/arctic#456]
### What happened?

When running a dimensional join on an Arctic table with partitions as a dimensional table, select Arctic table fields will encounter ClassCastException.

### Affects Versions

master/0.3.1

### What engines are you seeing the problem on?

Flink

### How to reproduce

Create a Arctic table with partitions and use the table as a dimensional table for dimensional join.Then select partition fields from Arctic table.

### Anything else

Output log in image form
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/49940747/194980770-a09f1398-dc5f-4320-bb2f-539c11aee0ee.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zstraw** [comment]
Dim table should be assigned a watermark field, which is not exist in the physical table. Arctic source will fill it by processing time automatically.
It's nessary to add a validation which checks the required watermark field.

**Comment by zhoujinsong** [comment]
> Dim table should be assigned a watermark field, which is not exist in the physical table. Arctic source will fill it by processing time automatically. It's nessary to add a validation which checks the required watermark field.

@zstraw  You may add this check logical in another issue and I will close this one.
