### ISSUE TITLE
[Improvement]: Partitioned Hive table should read correct data after alter table add a new column

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#527]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When we write the parquet file, we write the partition column as a field in the parquet file, so after adding the column, the old file reads the partition column as the value of the new field in order, so the data is read incorrectly. This happens when use the impala reads

### How should we improve?

According to Hive specifications, partition fields are not written to the parquet file as separate fields

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
We should not write the partition column into parquet files for Mixed Hive format table because Hive tables using `identify` partition transform only.
We can read the partition column from the `DataFile#partirionData`.

cc @shidayang

**Comment by hellojinsilei** [comment]
The problem is Impala caused. Impala maps parquet file according to the pos field, which leads to deviation of data read. You can set `parquet_fallback_schema_resolution = name` to resolve this problem
