### ISSUE TITLE
[Bug]: When table name is too long, allocate transaction id will fail

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#535]
### What happened?

When table name is too long, allocate transaction id will fail
![image](https://user-images.githubusercontent.com/109209550/198535699-b96ccfbf-fea9-4d2e-8889-a480a74f2db9.png)
My table name is "copy_arctic_dwd_order_valid_order" but in mysql table name is not complete

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

Create a long name Arctic table, and then insert data through flink

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hameizi** [comment]
The reason of this eaaor is: composite primary key is too long so that it is cut off, the main reason is the tableIdentify is too long. so do we should use the table id generated from the `table_metadata` table instead of tableIdentify(a string consisting of `catalog.db.table`)
@Aireed @zhoujinsong

**Comment by zhoujinsong** [comment]
> The reason of this eaaor is: composite primary key is too long so that it is cut off, the main reason is the tableIdentify is too long. so do we should use the table id generated from the `table_metadata` table instead of tableIdentify(a string consisting of `catalog.db.table`) @Aireed @zhoujinsong

I am agree with replacing table idetifier to table id in ams database tables. 
But Is there a way to change the primary key length limit in MySQL to fix this problem?

**Comment by hameizi** [comment]
The tableidentifier length limit has been extended in the new version
