### ISSUE TITLE
[Bug]: Flink ingestion task will commit an empty append file every 10 minutes

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#552]
### What happened?

When writing data into arctic through flink, every 10 minutes flink will commit an empty append file

### Affects Versions

0.3.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YesOrNo828** [comment]
You can also config `flink.max-continuous-empty-commits`= a big integer to avoid submitting the empty snapshot to arctic.
@shendanfengg

**Comment by shendanfengg** [comment]
This issue has been resolved in [ARCTIC-812]:Add flink sink properties to table default #813
