### ISSUE TITLE
[Bug]: When flink job fails over, flink job will commit a wrong transaction id

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#561]
### What happened?

When flink job fail over, flink job will commit a wrong transaction id. 
The wrong transaction id is 
![image](https://user-images.githubusercontent.com/109209550/199913933-b4b1585d-661e-4291-9edb-0000b67f6722.png)
And the right transaction id is 
![image](https://user-images.githubusercontent.com/109209550/199913889-ead8c7fa-832c-4ffa-a3a3-72b1872a6978.png)
The data associated with the wrong transaction id will be lost.
The problem can only be resolved by rebuilding the table and rewriting the data.

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

Flink

### How to reproduce

Insert data through flink and then make flink job failover

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zstraw** [comment]
The fix in Flink 1.14, 1.15 is invalid due to that the operator can not fetch restored checkpoint id through(ManagedInitializationContext#getRestoredCheckpointId) if there is no state in the operator.
