### ISSUE TITLE
[Improvement][AMS]: Database table structure reconstruction

### ISSUE THREAD

**Issue by hameizi** [NetEase/arctic#566]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1.Use table id instead of the full name of table
2.The table `contaber_metadata` should have name as the primary key

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Finished by #1372.
