### ISSUE TITLE
[Bug]: Not saving storage_configs to catalog_metadata correctly when creating a catalog

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#648]
### What happened?

Not saving storage_configs to catalog_metadata correctly when creating a catalog

### Affects Versions

0.4.0-SNAPSHOT

### What engines are you seeing the problem on?

AMS

### How to reproduce

Create Catalog with
Metastore : Hive Metastore
Table Format : Iceberg

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
when did you pull the code?  could you pull the latest code and have a try?

**Comment by Aireed** [comment]
Is that you have the previous process working ?  so your new thrift server can't start, so you get the error!  maybe you can check the ./logs/ams-all.log to find the cause

**Comment by zhongqishang** [comment]
@Aireed  I've probably found the reason.  I will open a PR.
