### ISSUE TITLE
[Bug]: trino380, when I select from arctic, using trino, there is an error: multiple entries with same key:1=d.key and 1=p

### ISSUE THREAD

**Issue by Sugariscool** [NetEase/arctic#652]
### What happened?

I use the architecture： kafka-flink-arctic, arctic-trino. 
The table  is created by flink and the structure is like following at arctic
`tb(p bigint,
e int,
t timestamp,
d MAP<int,double>,
primary key(t) not enforced)`
when I `select * from tb` , the data cannot be selected, and said `Query *** failed: Multiple entries with same key: 1=d.key and 1=p`
But I can use `select p,e,t from tb` or `select t,d from tb`,just only `select p,d from tb` will occur error. 
I want to know why? how can I repair?

### Affects Versions

arctic0.3.2

### What engines are you seeing the problem on?

Trino

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
cc @shidayang

**Comment by shidayang** [comment]
@Sugariscool Thanks for your report this bug

**Comment by Sugariscool** [comment]
Could you also update on version-0.3.2？

**Comment by Sugariscool** [comment]
Could you also update on version-0.3.2？
