### ISSUE TITLE
[Bug]: [flink1.15.2]when I select from flink, there is an error. it seems that there lost one jar file, but I  donnot know which one.

### ISSUE THREAD

**Issue by Sugariscool** [NetEase/arctic#653]
### What happened?

I execute `select * from table`, there is an error:
`[ERROR] Could not execute SQL statement. Reason: `
`java. lang. ClassNotFoundException: com.netease. arctic.shaded. org. apache. flink. streaming. connectors. kafka. table. KafkaConnector0ptions`

### Affects Versions

arctic-0.3.2

### What engines are you seeing the problem on?

Flink

### Anything else

flink1.15.2, hadoop3.1.3, arctic-0.3.2
I have copy the `arctic-flink-runtime-1.15-0.3.0.jar` to flink/lib and `flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar` to flink/lib
this is the flink lib
<img width="794" alt="截屏2022-11-19 18 01 43" src="https://user-images.githubusercontent.com/57608025/202848396-eebc63c1-ee79-4b31-89ba-8af06853a821.png">
arctic has `flink-connector-kafka-1.15.2.jar` and `commons-cli-1.4.jar` 
<img width="607" alt="截屏2022-11-19 18 03 19" src="https://user-images.githubusercontent.com/57608025/202848445-7ed85376-3ff5-47ec-80b8-61c5c0de933e.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lklhdu** [comment]
> cc @zstraw @lklhdu

I have solved this problem，and this is the pull request https://github.com/NetEase/arctic/pull/589. If users want to use arctic-flink under version 1.15, they can get the arctic flink runtime package by compiling the master branch

**Comment by Sugariscool** [comment]
> > cc @zstraw @lklhdu
> 
> I have solved this problem，and this is the pull request #589. If users want to use arctic-flink under version 1.15, they can get the arctic flink runtime package by compiling the master branch

I Have solved this problem by your method! thank you very much!
