### ISSUE TITLE
[Bug]: Derby does not support the `limit` syntax

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#660]
### What happened?

com.netease.arctic.ams.server.service.impl.PlatformFileInfoService#26

### Affects Versions

0.4.0-SNAPSHOT

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
OK. would you like to open a pr to fix it ?
