### ISSUE TITLE
[Bug]: Read BASE/CHANGE typed table in Trino error when the table name include schema name

### ISSUE THREAD

**Issue by ChenShuai1981** [NetEase/arctic#662]
### What happened?

trino> select * from "test_table#BASE" order by id;
Query 20221121_025527_00012_hnq5i failed: line 1:15: Schema must be specified when session schema is not set
select * from "test_table#BASE" order by id

trino> select * from "test_db.test_table#BASE" order by id;
Query 20221121_025538_00013_hnq5i failed: line 1:15: Schema must be specified when session schema is not set
select * from "test_db.test_table#BASE" order by id

trino> use test_db;
USE
trino:test_db> select * from "test_table#BASE" order by id;
 id | name  |          op_time           
----+-------+----------------------------
  1 | eric  | 2022-07-01 12:32:00.000000 
  5 | peter | 2022-07-02 00:11:40.000000 
  7 | randy | 2022-07-03 19:11:00.000000 
  8 | alice | 2022-07-04 11:11:00.000000 
(4 rows)

### Affects Versions

master

### What engines are you seeing the problem on?

Trino

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
cc @JamesIsHuang

**Comment by baiyangtx** [comment]
checked .

select via flink 

![image](https://user-images.githubusercontent.com/7732224/203016374-d02e796b-75f7-4935-a9ce-4cc6ac0c1b38.png)

select via spark 

![image](https://user-images.githubusercontent.com/7732224/203016451-c58d9e8f-a862-4c39-b6d8-e52cc4b58a53.png)

table schema 

![image](https://user-images.githubusercontent.com/7732224/203016540-9067a3f2-3f2a-4e68-a9c4-211996d660d8.png)

table files 

![image](https://user-images.githubusercontent.com/7732224/203016614-1bb7dff4-69b5-45a0-870d-2a84b22d5b9e.png)


seems spark problems

**Comment by baiyangtx** [comment]
for sql `insert into test_db.test_table values (7, 'randy', timestamp('2022-07-03 19:11:00'));

the flink connector write data 
![image](https://user-images.githubusercontent.com/7732224/203018747-3c71c926-d0b4-4059-a64d-1f7ecea1539b.png)


spark connector  write data 

![image](https://user-images.githubusercontent.com/7732224/203018800-630c3683-c4b5-4bb4-b20b-f3d6ab8c0317.png)

**Comment by baiyangtx** [comment]
spark connector writing data to file is ( value - 8h ).   it seems to spark handles timestamp-without-zone  via parse value as timestamp-with-zone and zone of spark configured, and spark writes data to file by UTC timestamp, so spark writes data as (value - 8h)
