### ISSUE TITLE
[Bug]: Wrong optimizer resource allocation display for local optimizer in Arctic Dashboard

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/arctic#669]
### What happened?

The display of optimizer resource allocation is wrong for local optimizer.

### Affects Versions

master

### What engines are you seeing the problem on?

Arctic Dashboard

### How to reproduce

- Scale-out a local optimizer and choose the parallelism to be `1`.
- The new optimizer resource allocation is shown to be `2 Core`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
cc @hameizi @shendanfengg

**Comment by hameizi** [comment]
coreNumber = parallelism + 1

**Comment by zhoujinsong** [comment]
> coreNumber = parallelism + 1

Could you please describe the reason for this logic？

**Comment by hameizi** [comment]
Because there is one main thread and the same number of executor threads as parallelism.

**Comment by zhoujinsong** [comment]
Does the main thread really cost one core for local optimizer?
In my option, the main thread is in SLEEP status for most time and cost fewer CPU resources.

**Comment by hameizi** [comment]
I will fix it.
