### ISSUE TITLE
[Improvement][AMS]:  log file should contain log level higher than current level 

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/arctic#678]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

currently,   ams-info.log contains info level log only.   the log file should contain logs which level higher than the current level.

### How should we improve?

1.  the log file should contain all logs which level higher than current file log level.
2.  the log file whose file size is usually small should be rolling by file size, meanwhile whose file size is usually bigger should be rolling by date. ( error log rolling by file size,  info log rolling by day, disable debug log in default)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
In my opinion, we should provide these log files：

- ams-error.log: log fetal and error messages and rolled with file size
- ams-info.log: log fetal/error/warn/info messages and rolled by day
- ams-debug.log log fetal/error/warn/info/debug messages and rolled by day and default to be disabled

All logs need to be output to a file instead of console.

**Comment by hameizi** [comment]
But, this may result in large info and debug log files.

**Comment by zhoujinsong** [comment]
According to my operation and maintenance experience, you will need all kinds of log information when tracing a problem, separate level layout makes this quiet hard.

**Comment by baiyangtx** [comment]
@hameizi if the `ams-info.log` file has too many results, that could only mean that should log so many logs at the INFO level.

**Comment by baiyangtx** [comment]
I think the backend thread shouldn't log to the INFO log at each schedule.   The INFO log is only triggered by user actions, the backed thread log nothing if anything is ok and if something is wrong write WARN or ERROR logs.

**Comment by wangtaohz** [comment]
I support that `ams-info.log` contains all fetal/error/warn/info logs, which brings great convenience when we have to know what happened before the error.

**Comment by hameizi** [comment]
> * ams-error.log: log fetal and error messages and rolled with file size
> * ams-info.log: log fetal/error/warn/info messages and rolled by day
> * ams-debug.log log fetal/error/warn/info/debug messages and rolled by day and default to be disabled

Based on the previous discussion, do we define log files like this?

**Comment by hameizi** [comment]
resolve this issue in #701
