### ISSUE TITLE
[Improvement]: Improve the log structure for local optimizer

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/arctic#685]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The log files of local optimizer are under folder `bin/${sys:log:lome}` and named like `ams-all.log` which is not easy to manage.

### How should we improve?

We should log output under folder `logs/optimizer_{container-name}_{group}_{optimizerId}` and named like `local_optimizer-info.log`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
cc @hameizi @hzluting @wangtaohz

**Comment by hameizi** [comment]
i will fix this in #701
