### ISSUE TITLE
[Bug][Spark]: Spark write timestamp value to parquet as UTC+0 hour. 

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/arctic#686]
### What happened?

When table schema contains a field as timestamp without-zone,  the value spark engines write to the parquet file is UTC+0, but should be the current timezone value.

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

Spark

### How to reproduce

checked .

select via flink 

![image](https://user-images.githubusercontent.com/7732224/203016374-d02e796b-75f7-4935-a9ce-4cc6ac0c1b38.png)

select via spark 

![image](https://user-images.githubusercontent.com/7732224/203016451-c58d9e8f-a862-4c39-b6d8-e52cc4b58a53.png)

table schema 

![image](https://user-images.githubusercontent.com/7732224/203016540-9067a3f2-3f2a-4e68-a9c4-211996d660d8.png)

table files 

![image](https://user-images.githubusercontent.com/7732224/203016614-1bb7dff4-69b5-45a0-870d-2a84b22d5b9e.png)

seems spark problems

### Anything else

for sql `insert into test_db.test_table values (7, 'randy', timestamp('2022-07-03 19:11:00'));

the flink connector write data 
![image](https://user-images.githubusercontent.com/7732224/203018747-3c71c926-d0b4-4059-a64d-1f7ecea1539b.png)

spark connector  write data 

![image](https://user-images.githubusercontent.com/7732224/203018800-630c3683-c4b5-4bb4-b20b-f3d6ab8c0317.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
spark connector writing data to file is ( value - 8h ). it seems to spark handles timestamp-without-zone via parse value as timestamp-with-zone and zone of spark configured, and spark writes data to file by UTC timestamp, so spark writes data as (value - 8h)

**Comment by hellojinsilei** [comment]
It seems that it is not only the arctic table that has problems. For the iceberg table, after my test, flink writes the iceberg table and the time read by spark will also be increased as (value + 8h).
After checking, it is confirmed that spark automatically converts the UTC timestamp to the local time zone (GMT+8) when reading timestamp data.  The timestamps written by flink into the Iceberg is the UTC timezone value.  When the spark reads the iceberg time, the timestamp is increased as (value + 8h)

**Comment by hellojinsilei** [comment]
Add the following configuration to spark-default.conf:

spark.driver.extraJavaOptions -Duser.timezone=UTC
spark.executor.extraJavaOptions -Duser.timezone=UTC
spark.sql.session.timeZone=UTC

Making sure that the same timeZone is written and read can temporarily solve this problem

**Comment by hellojinsilei** [comment]
> @hellojinsilei Can we solve this problem by setting timzeone to GTM+8 in flink?

Flink cannot write timestamp type with timeZone

@lklhdu Can we do that?

**Comment by lklhdu** [comment]
> > @hellojinsilei Can we solve this problem by setting timzeone to GTM+8 in flink?
> 
> Flink cannot write timestamp type with timeZone
> 
> @lklhdu Can we do that?

In my understanding, TIMESTAMP is a field in Flink without a time zone attribute, if we need to set a time zone for the field, we should use TIMESTAMP WITH LOCAL TIME ZONE.
