### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by moresun** [NetEase/arctic#697]
### What happened?

![image](https://user-images.githubusercontent.com/29471995/203240890-99adcf5a-b7cf-4e13-994b-5e0fd32e7279.png)

使用flink官方文档写入cdc数据，然后从spark那边启动读取内容，报错；catalog.database.tablename 都尝试过无法读取，spark-sql也是这样的错误

### Affects Versions

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moresun** [comment]
ams上terminal面执行语句可以查看，表里面有这些记录

**Comment by moresun** [comment]
![5bwsYT0Y5d](https://user-images.githubusercontent.com/29471995/203241985-00d46254-d9a1-4932-ac9e-48e32b29c307.jpg)

**Comment by HuangFru** [comment]
https://github.com/NetEase/arctic/issues/691
我觉得你碰到的问题和这个issue一样。
当你使用quick-start的docker-compose 启动ams容器时，你的容器中有一个/tmp/arctic/warehouse 目录对应local_catalog的warehouse，这是在你容器中的。
当你使用spark读的时候spark会在你使用spark的地方（如果是本机那就会在本机目录下）去寻找/tmp/arctic/warehouse，spark找不到这个目录，更没有办法同步ams容器里这个目录的数据，所以会报找不到

**Comment by HuangFru** [comment]
可以参考docker-compose文件中挂载的容器卷 ./data 目录，就是用来同步ams和flink容器warehouse目录数据的

**Comment by HuangFru** [comment]
如果是本地使用的spark话可以通过软链接 {docker_path}/data ， /tmp/arctic/warehouse/ 这个两个目录应该是可行的

**Comment by moresun** [comment]
我想往s3上面写 我看环境中都没有相关jar包 也没有提供案例

**Comment by moresun** [comment]
![5bwsYT0Y5d](https://user-images.githubusercontent.com/29471995/203241941-632129fb-446c-4806-8180-cc301a6543e1.jpg)

**Comment by HuangFru** [comment]
https://github.com/NetEase/kyuubi-arctic-playground
可以看一下这个项目，是kyuubi和arctic共建的一个演示项目，里面使用了s3储存
