### ISSUE TITLE
[Improvement]: Support for regular expressions to match database name for Hive Metastore 

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#712]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The existing HMS has a large number of hive tables, and all the databases and tables have to be loaded each time. 
Support for regular matching of database

### How should we improve?

Add an input when creating a catalog to support regular expressions to match database names

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@zhoujinsong Sorry for not being clear.

We are going to have iceberg format in our existing cluster, but there are a lot of hive DBs and tables in the existing cluster that I don't need to care about and I don't want to show them in AMS, so I want to exclude them.

Regarding the two points you mentioned both are optimizations that come with this improvement.

**Comment by zhongqishang** [comment]
Also, when creating a Catalog format can only choose hive or iceberg, but in fact, both may exist in HMS.

**Comment by zhoujinsong** [comment]
> @zhoujinsong Sorry for not being clear.
> 
> We are going to have iceberg format in our existing cluster, but there are a lot of hive DBs and tables in the existing cluster that I don't need to care about and I don't want to show them in AMS, so I want to exclude them.
> 
> Regarding the two points you mentioned both are optimizations that come with this improvement.

Thanks for introducing the detail of your use case. 
And welcome to provide a PR to achieve this improvement more quickly.

**Comment by zhoujinsong** [comment]
> Also, when creating a Catalog format can only choose hive or iceberg, but in fact, both may exist in HMS.

Yes, we are planning to support multiple formats in a catalog. 
Are you interested in joining our development WeChat group, we can discuss some future features here.

**Comment by zhongqishang** [comment]
@huiyuanz Can you help me with the frontend work?

**Comment by zhoujinsong** [comment]
> @huiyuanz Can you help me with the frontend work?

AFAIK, filtering databases and tables on the backend is enough for this feature?

**Comment by zhongqishang** [comment]
@zhoujinsong 
I'm going to add a regular expression input to the catalog creation page to filter the databases.
I've done it on the back end [1], not so good on the front end and have a few questions.

[1] : https://github.com/zhongqishang/arctic/tree/ARCTIC-712

**Comment by zhoujinsong** [comment]
> @zhoujinsong I'm going to add a regular expression input to the catalog creation page to filter the databases. I've done it on the back end [1], not so good on the front end and have a few questions.
> 
> [1] : https://github.com/zhongqishang/arctic/tree/ARCTIC-712

How do you think put the configuration into catalog properties?
In my option, filter expression is not required for creating every catalog.

**Comment by zhoujinsong** [comment]
By the way, do you want to filter the database on the engine side (flink/spark/trino) too?

**Comment by zhongqishang** [comment]
> How do you think put the configuration into catalog properties?

This should be a good choice.

> In my option, filter expression is not required for creating every catalog.

In my scenario, filtering the database will only happen if an existing HMS is loaded into the AMS, other scenarios it should not be necessary.

> By the way, do you want to filter the database on the engine side (flink/spark/trino) too?

The catalog registered on the engine side uses the AMS, so filtering should depend on whether the databases exist in the AMS or not, What do you think?
