### ISSUE TITLE
[Bug]: File name can not see when upload file to create catalog

### ISSUE THREAD

**Issue by shidayang** [NetEase/arctic#718]
### What happened?

![image](https://user-images.githubusercontent.com/26699250/203462831-40988557-7e83-4155-908a-4e41f6a0046f.png)

Can not see the name of  core-site and hdfs-site, but they have upload successed

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
cc @huiyuanz

**Comment by huiyuanz** [comment]
Didn't reproduce well, try to see if it can be reproduced in the latest version

**Comment by shidayang** [comment]
OK， Fixed in new version
