### ISSUE TITLE
[Bug]: Failed to get optimizerGroup tables when fail to open metadata

### ISSUE THREAD

**Issue by XBaith** [NetEase/arctic#756]
### What happened?

AMS cannot list tables in Optimizers dashboard when fail to open metadata file:
For instances:
- Permission denied: user=root, access=EXECUTE, inode="/path":yyy:supergroup:drwxrwxrw-
- Table metadata not find(Someone manually moved/deleted it)

AMS Optimizer dashboard should display available tables as possible as it could.

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

Manually moved/deleted the metadata and try to list tables in Optimizers dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hameizi** [comment]
Thanks for you comment, this issue will be fix in #743

**Comment by zhoujinsong** [comment]
Fixed in #757.
