### ISSUE TITLE
[Improvement]: improve optimizing status display

### ISSUE THREAD

**Issue by majin1102** [NetEase/arctic#780]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The optimizing page display on MBP would be like this:
![image](https://user-images.githubusercontent.com/5731171/204469594-99a30d97-36ed-4ccc-940d-dc4f6d41fe26.png)

This presentation has following shortcomings：
1. minor/major/full optimizing status terms was not fully presented
2. there's no highlighting between optimizing and no optimizing status
3. if a lot of tables under pending status, there should be warning

### How should we improve?

1. change title of status to optimizing status
2. add dots of different color before optimizing status items with optimizing green, pending yellow and idle grey
3. change item of MinorOptimizng, MajorOptimizing and FullOptimizing to minor, major and full, change Pending to pending and change Idle to idle

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Should we capitalize the first letter for status like :
`Idle` `Pending` `Minor` `Major` and `Full`?

**Comment by majin1102** [comment]
> Should we capitalize the first letter for status like : `Idle` `Pending` `Minor` `Major` and `Full`?

I don't think so, because this is content, not title or specific

**Comment by zhoujinsong** [comment]
Okay, Displaying the status in lower case seems good to me.
