### ISSUE TITLE
[Bug][AMS]: Not auto jump to login page if visit some page without login 

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/arctic#782]
### What happened?

![image](https://user-images.githubusercontent.com/7732224/204495222-80e9b1e8-c7d9-4910-b1bc-91293b266def.png)

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

AMS should reject to login page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
i will try to fix it!
