### ISSUE TITLE
[Improvement]: Validate required properties when creating catalog

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/arctic#797]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Arctic support creating catalogs on AMS Dashboard now. We need check the requested properties when creating catalogs.

### How should we improve?

Different catalog types need different required properties:

- Arctic Metastore requires `warehouse.dir`
- Hadoop requires `warehouse`
- Custom requires `catalog-impl`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
Could we unify the `warehouse.dir` and `warehouse` property names in the Arctic Metasotre and Hadoop catalog types?

**Comment by zhoujinsong** [comment]
> Could we unify the `warehouse.dir` and `warehouse` property names in the Arctic Metasotre and Hadoop catalog types?

Unify the property name looks good to me, but we need to handle the compatibility problems with existed catalog.
How do you think ? @baiyangtx
