### ISSUE TITLE
[Bug]: Spark MOR read the data written by flink before insert overwrite

### ISSUE THREAD

**Issue by zstraw** [NetEase/arctic#804]
### What happened?

1.
 ```
CREATE TABLE IF NOT EXISTS user (
    id INT,
    name string,
    ts TIMESTAMP,
    PRIMARY KEY(id)
) USING arctic 
PARTITIONED BY (days(ts));
```

2. insert into by flink
```
INSERT INTO user VALUES 
(1, "eric", timestamp("2022-07-02 12:32:00")),
(2, "frank", timestamp("2022-07-02 09:11:00")),
(3, "lee", timestamp("2022-07-02 10:11:00")); 
```

3.
```
INSERT OVERWRITE user VALUES 
(4, "eric", timestamp("2022-07-01 12:32:00")),
(5, "frank", timestamp("2022-07-02 09:11:00")),
(6, "lee", timestamp("2022-07-01 10:11:00"));
```

4. Now, the data select * from user is right.
5. insert into some data by flink again, then the data written by flink at first time will be also read.

### Affects Versions

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
@zstraw Could you confirm the version of saprk? I guess may be spark version is not 0.4

**Comment by wangtaohz** [comment]
I read your table @zstraw, but I didn't reproduce it with the latest master branch (0.4.0-SNAPSHOT).

![image](https://user-images.githubusercontent.com/103108928/205227028-2293b7aa-b78b-4372-bf77-f3e00bfe922f.png)

![image](https://user-images.githubusercontent.com/103108928/205227184-844c7216-8405-4487-bec1-1575cd1f4b03.png)
![image](https://user-images.githubusercontent.com/103108928/205227206-8906dac3-a307-47f4-a76e-5b553db43f1f.png)
![image](https://user-images.githubusercontent.com/103108928/205227226-7ba049ef-a54a-4dcb-8f6f-026ea3972d74.png)

**Comment by zstraw** [comment]
Thanks a lot. After my retry by building package from master branch, I can not reproduce it again.
