### ISSUE TITLE
[Bug]: When a table has too many small files to be optimized, it will cause AMS OOM

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#826]
### What happened?

![image](https://user-images.githubusercontent.com/109209550/205532314-f8acde5c-ff5a-4081-aca8-d9d0c4ad7085.png)
When there are too many small files to be optimized with a primary key table, and then optimize causes AMS OOM
![image](https://user-images.githubusercontent.com/109209550/205533280-cb8a81af-00f2-428d-a71b-5919d6ae1745.png)
We can see that optimizing a small file of over 600,000 in an AMS configuration with 32G of RAM results in oom

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

1. Create table and write a lot of data for a long time without optimize
2. Set props ‘optimize.enable’ = true 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YesOrNo828** [comment]
After an offline discussion with @zstraw, we found that the Flink application job recovers from any checkpoint which occurs by submitting the same transaction id in the first two snapshots. IMO, `checkpointId` should be incremented by 1 in the `prepareSnapshotPreBarrier` of the `ArcticFileWriter` operator.
