### ISSUE TITLE
[Improvement]: Improvement of optimizer management UI interface

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#869]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1. When we select `All Groups`, we don't know the optimizer group of each table.

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/103108928/206076690-7b71d3ba-6bd4-43e6-9618-b7af126651a6.png">

2. refresh resource info after click `Scale-Out` button to match actual resource stats.
3. don't close scale-out dialog after clicking OK before backend returning back
4. in catalogs module, when catalog list is empty, don't show `NO DATA`.
5. modify title of `What is arctic` to `What is Arctic` in front page.
6. logo of arctic dashboard could be linked to front page
7. stay at former tab page after refreshing optimizers management UI, as well as table details UI.

### How should we improve?

Add a new column of `Optimizer Group`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
cc @huiyuanz @hameizi
