### ISSUE TITLE
[Bug]: Spark select table will throw FileNotFoundException

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#873]
### What happened?

This is an occasional bug：
Use spark SQL insert overwrite lots of partitions, then execute select table will throw FileNotFoundexception

![image](https://user-images.githubusercontent.com/52364847/206133970-e49ad14e-68df-43d4-92ef-c386432b4c47.png)

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

Core, Spark

### How to reproduce

Step1: Create an unkeyed table
Step2: Insert overwrite sink table select from the source table
Step3: Select from the sink table

notice: The source table needs to have multiple partitions

### Anything else

Query the file in the hdfs where an error occurs. No file exists in the directory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@hellojinsilei I am wondering the status of this bug.
Have you addressed the cause ?

**Comment by baiyangtx** [comment]
This happened in HuaTai's branch and was only reproduced in 0.3.x branch, remove critical tag

**Comment by hellojinsilei** [comment]
This bug is caused by file write failure during insert overwrite
