### ISSUE TITLE
[Bug][Optimize]: Optimize Checker not working after failing to load table over few times

### ISSUE THREAD

**Issue by XBaith** [NetEase/arctic#875]
### What happened?

```
ERROR [Metastore Scheduled Check Worker 0] [com.netease.arctic.table.TableMetaStore] [] - run with catalog ugi request failed. UGI is root (auth:SIMPLE)
org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: hdfs://namenode1/user/hive/warehouse/test.db/arctic_optimize_demo/metadata/00123-d4361cee-281a-4538-991c-2fccfcd74257.metadata.json
```

Effects:
- Cannot load new tables to cache
- Cannot optimize new table
- Cannot display the tables in optimize dashboard

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

1. Delete current metadata.json to make table invalid
2. Start AMS and wait for a while

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
Thanks for your report. I have reproduced this bug and will fix it ASAP.
