### ISSUE TITLE
[Bug]: Optimize commit time of the web-page and the database are inconsistent

### ISSUE THREAD

**Issue by XBaith** [NetEase/arctic#880]
### What happened?

The timestamp of the database is UTC, but the timestamp on optimize dashboard is UTC+8

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XBaith** [comment]
Will the displayed commit time be automatically adjusted according to the user's time zone?

**Comment by XBaith** [comment]
And can you sort optimization history by commit time?

**Comment by zhoujinsong** [comment]
That's true.
All the timestamp values are stored as long type(UTC) in AMS backend and transformed to string type using the user's local time zone in AMS Dashboard.
Has this implementation brought you any misunderstandings?

**Comment by XBaith** [comment]
> 

Great, I understood. And maybe we can adds the function of sorting in dashboard table.

**Comment by zhoujinsong** [comment]
> > 
> 
> Great, I understood. And maybe we can adds the function of sorting in dashboard table.

Looks good to me. 
Many tables and lists in the AMS Dashboard should support sorting by different fields to improve the user experience.
I will open another issue to track this.
