### ISSUE TITLE
[Improvement]: Refactor the orphan files clean when loading the valid ContentFiles

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#883]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When the orphan files clean service gets all the valid ContentFiles, it will plan all files for each snapshot, which will bring performance problems.
```
   private static Set<String> getValidDataFiles(TableIdentifier tableIdentifier, ArcticFileIO io,
                                               UnkeyedTable internalTable) {
    Set<String> validFiles = new HashSet<>();
    Iterable<Snapshot> snapshots = internalTable.snapshots();
    int size = Iterables.size(snapshots);
    LOG.info("{} get {} snapshots to scan", tableIdentifier, size);
    int cnt = 0;
    for (Snapshot snapshot : snapshots) {
      cnt++;
      int before = validFiles.size();
      io.doAs(() -> {
        // valid data files
        for (FileScanTask scanTask
            : internalTable.newScan().useSnapshot(snapshot.snapshotId()).planFiles()) {
          if (scanTask.file() != null) {
            validFiles.add(getUriPath(scanTask.file().path().toString()));
            scanTask.deletes().forEach(file -> validFiles.add(getUriPath(file.path().toString())));
          }
        }
        return null;
      });
      LOG.info("{} scan snapshot {}: {} and get {} files, complete {}/{}", tableIdentifier, snapshot.snapshotId(),
          formatTime(snapshot.timestampMillis()), validFiles.size() - before, cnt, size);
    }

    return validFiles;
  }
```

### How should we improve?

It's better to load `MetadataTableType.ALL_MANIFESTS` to get all the content file entries in manifest files, like what `org.apache.iceberg.spark.actions.BaseSparkAction#buildValidDataFileDF` does.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
Is it duplicated with this issue #915 ?

**Comment by wangtaohz** [comment]
> Is it duplicated with this issue #915 ?

No, there's no relation between them. This issue is just an improvement in performance.

**Comment by wangtaohz** [comment]
When failing to delete the file(the file does not exist), we should ignore the exception.

@shendanfengg
