### ISSUE TITLE
[Bug]: When optimize fails to commit and then deletes a file, the optimize task will fail when retrying

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#910]
### What happened?

When optimize fails to commit and then deletes a file, the optimize task will fail when retrying.
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4164885277312037946 skey=@crypt_6bd6fcc2_fff7adbb1382a57fa2072b9d3eab009c mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/109209550/206708452-a26b2e26-b083-4012-8832-7abf37dcca1a.jpg)
We can see that the first commit failed and a file was deleted afterwards.
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2928279045979481811 skey=@crypt_6bd6fcc2_fff7adbb1382a57fa2072b9d3eab009c mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/109209550/206708430-0797814f-afa0-4e88-9674-ce28c9fe044a.jpg)
Failed to get status for file: hdfs://nameservice1/user/hive/warehouse/realtime arctic v3.db/zl ual nonrealtime deviceprofile/hive/hdfs par=20221206/1670310415839 5957073387926017638/1-B-6002581311138640498-00000-9064569570000000001.parquet. caused by File does not exist: hdfs://nameservice1/user/hive/warehouse/realtime arctic v3.db/zl uanonrealtime device profile/hive/hdfs par=20221206/1670310415839 5957073387926017638/1-B-6002581311138640498-00000-906456957-0000000001.parquet
When optimize retries, optimize loads the deleted file again, causing the task to fail.

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

Don't know how to reproduce the problem

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Overwrite hive table failed when committing iceberg table success and committing HMS failed.
We should ignore committing errors to HMS when committing iceberg successfully.
