### ISSUE TITLE
[Improvement]: More elegant display of error messages in terminal

### ISSUE THREAD

**Issue by majin1102** [NetEase/arctic#913]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

So far terminal log shows error message as below:

![image](https://user-images.githubusercontent.com/5731171/206718961-c8fc36c6-662b-4755-b457-d0154c13772f.png)

There could be three points to improve:

1. show red Error status instead of green Finished status
2. use red color for error message and error stacks
3. display `/t` for stack rows

### How should we improve?

1. return Error status when throwing error instead of Finished
2. split error logs and processing logs into different return packages
3. UI display red for Error status and error logs.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
cc @huiyuanz

**Comment by zhoujinsong** [comment]
Resolved by #1006
