### ISSUE TITLE
[Bug]: Flink can not restore from checkpoint if pending files are removed by Optimizer 

### ISSUE THREAD

**Issue by zstraw** [NetEase/arctic#915]
### What happened?

Flink commiter would produce some pending manifest files. They would be committed(cleaned) after ckp completed.
If these files are removed by Optimizer because they are orphan files, flink task will not be able to recover from the checkpoint anymore.

### Affects Versions

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@zstraw I would like to set this bug to critical priority if it will block the Flink job recovering process.
Do you have any ideas for the solution yet?

**Comment by zstraw** [comment]
> @zstraw I would like to set this bug to critical priority if it will block the Flink job recovering process. Do you have any ideas for the solution yet?

I have not thought it over yet. Maybe it can be sovled by keeping all pending file in Flink state or config a longer expire time in Optimizer.

**Comment by zhoujinsong** [comment]
I think the key to dealing with this issue may be the need to skip these pending files that are still needed in the cleanup process in AMS. There are two key points about this implementation:

- Whether AMS can find which pending files are still needed?
- Does AMS can skip some specific files when cleaning up?

How do you think? @wangtaohz  @zstraw

**Comment by zstraw** [comment]
> * Whether AMS can find which pending files are still needed?

I think AMS may not determine whether the pending files are needed. It depends on users.
User may run a task, then stop it. And the task can be deprecated forever or restart it after a long time.

We can think it as useless only when task has been removed or the state has been cleared.

> * Does AMS can skip some specific files when cleaning up?

AMS can skip the pending files which we can specific the pending files to a designated directory or recognise them by the name of files. 

But it may keep some pending files which can be exist forever. May be we can provide an API to list/delete these pending files by tables/tasks, then integrating them into platform.

**Comment by zhoujinsong** [comment]
I think AMS can keep the pending files that are required by the latest Flink committed snapshot.
If a new Flink job (event the old one) commits a new snapshot, the pending files can be expired.

If there are no new snapshot committed by Flink job, keeping the lastest pending file is okay for me.

**Comment by wangtaohz** [comment]
> to solve Case2:
the orphan file clean service of AMS should not delete the temporary files of the flink state, whose file name is started with flink.job-id. These files are supposed to be deleted by the flink job itself.

the solution is described in #930
