### ISSUE TITLE
[Improvement]: Too many Full GC after starting AMS

### ISSUE THREAD

**Issue by XBaith** [NetEase/arctic#916]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I think too many resident objects are saved in the old generation, which leads to frequent full gc, especially when AMS is just started

![image](https://user-images.githubusercontent.com/54210725/206969226-8181fc90-7dfd-42f7-8a0a-46d79d55232b.png)

- AMS run with 10G heap memory in docker
- Handle 1253 tables
```
VM Flags:
Non-default VM flags: -XX:CICompilerCount=4 -XX:GCLogFileSize=10485760 -XX:InitialHeapSize=2147483648 -XX:+ManagementServer -XX:MaxHeapSize=10737418240 -XX:MaxNewSize=5368709120 -XX:MinHeapDeltaBytes=524288 -XX:NewRatio=1 -XX:NewSize=1073741824 -XX:NumberOfGCLogFiles=10 -XX:OldSize=1073741824 -XX:+PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:SurvivorRatio=3 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseFastUnorderedTimeStamps -XX:+UseGCLogFileRotation -XX:+UseParallelGC 
Command line:  -Dlog.home=/usr/local/ams/arctic-0.4.0-SNAPSHOT/logs -Dlog.dir=/usr/local/ams/arctic-0.4.0-SNAPSHOT/logs -Duser.dir=/usr/local/ams/arctic-0.4.0-SNAPSHOT -Xloggc:/usr/local/ams/arctic-0.4.0-SNAPSHOT/logs/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=10M -Xms2048m -Xmx10240m -XX:MaxPermSize=128m -verbose:gc -XX:+PrintGCDetails -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:NewRatio=1 -XX:SurvivorRatio=3
```
Improve AMS corresponding efficiency, reduce full gc times.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XBaith** [comment]
After setting `table-expire.enabled` to `false` old generation and full GC times much less. I think epxire table snapshot may cost a lot of memory. So should we consider disabing  `table-expire.enabled` by default?

![image](https://user-images.githubusercontent.com/54210725/207039335-1a23acc9-ee69-45eb-a74e-1152d8aee334.png)

**Comment by wangtaohz** [comment]
Table Expiring will cost a lot of memory, if there are too many snapshots to be expired and too many files to be deleted,
that is because iceberg loads all files should be deleted into a Set when expiring.

**Comment by wangtaohz** [comment]
> Table Expiring will cost a lot of memory, if there are too many snapshots to be expired and too many files to be deleted, that is because iceberg loads all files should be deleted into a Set when expiring.

But if we set `cleanExpiredFiles` to `false`, like 
```
    table.expireSnapshots()
        .retainLast(1)
        .expireOlderThan(olderThan)
        .cleanExpiredFiles(false)
        .commit();
```

Iceberg will skip delete files and avoid the memory cost, and these files will be left as orphan files which could be cleaned by orphan-files clean later.

**Comment by zhoujinsong** [comment]
In my opinion, expired files are better cleaned up in time.
But we still need to find the solution for the full gc problem,

**Comment by XBaith** [comment]
> 

Good suggestion, passing `false` to cleanExpiredFiles function reduce momery size.
But is it means that frequence full gc will be pushed down to `orphan-files` cleanup?

**Comment by wangtaohz** [comment]
It may not. Because orphan-files clean's memory cost depends on the remaining valid files, it will not load the files to delete into memory.

So, unless you keep too many snapshots, orphan-files clean's memory cost is limited.

**Comment by wangtaohz** [comment]
> In my opinion, expired files are better cleaned up in time. But we still need to find the solution for the full gc problem. For example, when there are too many snapshots that need to expire, can we split snapshots that need to expire to protect form loading too many files into memory?

Iceberg's `ExpireSnapshots` didn't offer much flexibility, but it suggests using the ActionAPI like `ExpireSnapshotsSparkAction`. 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/103108928/207284583-e326a731-3d7c-4cd8-b6e5-651b70ff0df8.png">

But, I'm not sure whether the `ExpireSnapshotsSparkAction` has this memory problem.

**Comment by XBaith** [comment]
AMS old generation still be filled after running for a period of time(manage 1500+ tables from different cluster). Expried snapshots issue seems not root case.
```
root@arctic-hadoop-58857b5575-nlqr6:/usr/local/ams/arctic-0.4.0-SNAPSHOT# jstat -gcutil 22 5000
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
  0.00   0.00 100.00 100.00  95.63  91.63   1030  163.357  3464 13112.846 13276.203
  0.00   0.00 100.00 100.00  95.63  91.63   1030  163.357  3465 13116.803 13280.160
  0.00   0.00 100.00 100.00  95.63  91.63   1030  163.357  3466 13120.819 13284.176
  0.00   0.00 100.00 100.00  95.63  91.63   1030  163.357  3467 13124.938 13288.294
  0.00   0.00 100.00 100.00  95.63  91.63   1030  163.357  3468 13128.869 13292.225
```
I analyzed the class occupancy of jvm memory, see below:
```
root@arctic-hadoop-58857b5575-nlqr6:/usr/local/ams/arctic-0.4.0-SNAPSHOT# jmap -histo:live 22 | head -n 100

 num     #instances         #bytes  class name
----------------------------------------------
   1:      91202458     2918478656  java.util.HashMap$Node
   2:      26024231     1249163088  java.nio.HeapByteBuffer
   3:      48450093     1162802232  java.lang.Long
   4:      26033418     1075403008  [B
   5:      10154087      915681488  [C
   6:       2791975      707657768  [Ljava.util.HashMap$Node;
   7:      10152692      243664608  java.lang.String
   8:       3048670      146336160  java.util.HashMap
   9:       5312325      127495800  org.apache.iceberg.relocated.com.google.common.collect.ImmutableMapEntry
  10:       1108169       91948280  [Lorg.apache.iceberg.relocated.com.google.common.collect.ImmutableMapEntry;
  11:       3023466       72563184  org.apache.iceberg.util.SerializableMap
  12:       2740418       65770032  org.apache.iceberg.relocated.com.google.common.collect.ImmutableMapEntry$NonTerminalImmutableMapEntry
  13:       2001393       64044576  java.util.concurrent.ConcurrentHashMap$Node
  14:       1953537       62513184  java.util.Hashtable$Entry
  15:        503897       52405288  org.apache.iceberg.GenericDataFile
  16:        554272       44341760  org.apache.iceberg.BaseSnapshot
  17:         33899       31063472  [Ljava.util.concurrent.ConcurrentHashMap$Node;
  18:        549410       25196144  [Ljava.lang.Object;
  19:        705366       22571712  org.apache.iceberg.types.Types$NestedField
  20:        562052       22482080  org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap
  21:        503880       20155200  org.apache.iceberg.BaseFileScanTask
  22:        549461       17582752  org.apache.iceberg.TableMetadata$SnapshotLogEntry
  23:        504070       16130240  org.apache.iceberg.PartitionData
  24:       1007838       16125408  org.apache.iceberg.SerializableByteBufferMap
  25:        787013       12592208  java.lang.Integer
  26:        504028       12115176  [J
  27:          3944       10844688  [Ljava.util.Hashtable$Entry;
  28:        503881        8062536  [Lorg.apache.iceberg.DeleteFile;
  29:        305244        7325856  org.apache.iceberg.TableMetadata$MetadataLogEntry
  30:          8479        5709232  [Lorg.apache.iceberg.types.Types$NestedField;
  31:         64610        4651920  org.apache.avro.JsonProperties$2
  32:         14051        2548016  [Lorg.apache.avro.io.parsing.Symbol;
  33:        103158        2475792  java.util.concurrent.ConcurrentLinkedQueue$Node
  34:         68592        1646208  java.util.concurrent.ConcurrentLinkedQueue
  35:         12676        1424104  java.lang.Class
  36:         28149        1351152  com.google.gson.internal.LinkedTreeMap$Node
  37:         26577        1275696  org.apache.avro.Schema$Field
  38:         16022        1050648  [Ljava.util.Map$Entry;
  39:         61918         990688  java.util.HashMap$EntrySet
  40:         18613         744520  java.util.LinkedHashMap$Entry
  41:         30168         724032  org.apache.avro.reflect.MapEntry
  42:         26509         715912  [Ljava.lang.String;
  43:         23821         571704  java.util.ArrayList
  44:         17236         551552  org.apache.avro.Schema$LockableArrayList
  45:         11309         504576  [I
  46:         12287         491480  org.apache.avro.Schema$UnionSchema
  47:          5482         482416  java.lang.reflect.Method
  48:          8824         423552  com.google.gson.internal.LinkedTreeMap
  49:         24433         390928  com.fasterxml.jackson.databind.node.IntNode
  50:          5640         360960  java.util.concurrent.ConcurrentHashMap
  51:          2623         356728  com.netease.arctic.ams.server.model.BaseOptimizeTask
```

We should need to look for deeper reasons @wangtaohz @zhoujinsong

**Comment by Aireed** [comment]
OK，i will follow the problem。 I will feedback here if there is some progress.  @XBaith

**Comment by wangtaohz** [comment]
I think this PR https://github.com/NetEase/arctic/pull/929 will help. 

As from your JVM dump result, the memory is mainly occupied by the metrics of the iceberg DataFile.

**Comment by wangtaohz** [comment]
Fetching file sequence numbers during the optimizing plan was reported to be another process cost memory,
because a map in `SequenceNumberFetcher` cached all file paths and sequence numbers in memory.

After replacing the cache in memory with a map in file like [MapDB](https://jankotek.gitbooks.io/mapdb/content/), the OOM of AMS during the optimizing plan was solved.

However, the cache in `SequenceNumberFetcher` wouldn't be the only cause of the OOM problem, since all `FileScanTask` are also cached in memory, which is supposed to occupy more memory than `SequenceNumberFetcher`.

**Comment by majin1102** [comment]
Thanks for feeding back.

If improvement as above could solve your problem, it would be very nice of you to tell us here and close this issue, if not , we could continue following this issue.

**Comment by XBaith** [comment]
> Thanks for feeding back.
> 
> If improvement as above could solve your problem, it would be very nice of you to tell us here and close this issue, if not , we could continue following this issue.

Replacing the cache in `SequenceNumberFetcher ` by disk map can decrease JVM heap pressure, but AMS will still be unavilable after few hours. I think we should we should figure out how to use less heap memory to plan exsting iceberg tables which has a certain number of small files ASAP.
