### ISSUE TITLE
[Bug]: After log in and click on any link, occur exception

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#931]
### What happened?

After log in and click on any link, an exception pops up and back home page and I see an error reported on the console.
```
Uncaught (in promise) TypeError: (t || []).forEach is not a function
    at chunk-06619d26.be7ef06b.js:1:16850
    at d (chunk-vendors.c73d2b69.js:47:735548)
    at Generator._invoke (chunk-vendors.c73d2b69.js:47:736874)
    at Generator.next (chunk-vendors.c73d2b69.js:47:735977)
    at o (chunk-vendors.c73d2b69.js:1:339865)
    at s (chunk-vendors.c73d2b69.js:1:340068)
```

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

I have not found a way to consistently reproduce

### Anything else

![image](https://user-images.githubusercontent.com/16421989/207312546-43a0873c-fff7-4f8d-8926-38088111b271.png)

![image](https://user-images.githubusercontent.com/16421989/207317063-294512eb-e4cf-466a-8916-fe2ed15921a8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
cc @huiyuanz

**Comment by zhongqishang** [comment]
@huiyuanz This did not happen after I redeployed on k8s.
close.
