### ISSUE TITLE
[Improvement][Flink]: Support all logstore configuration items to be configured in table properties

### ISSUE THREAD

**Issue by zstraw** [NetEase/arctic#933]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now log-store configuration was doced in table properties. But some config is invalid in table which should be set in flink sql hint.
It's necessary to uniformly manage all log-store properties in table.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
@zstraw  Could you share some example properties which are invalid in table properties?

**Comment by zstraw** [comment]
> @zstraw Could you share some example properties which are invalid via the flink SQL hint?

As I known, 'log-store.consistency-guarantee.enabled' and 'log.consumer.changelog.modes' are invalid in table properties, not invalid in flink sql hint.
