### ISSUE TITLE
[Bug]: The data accuracy is wrong when querying the upsert type table with “where” statement

### ISSUE THREAD

**Issue by shidayang** [NetEase/arctic#945]
### What happened?
When I use the query statement with "where" to query the upsert table, I will get incorrect results

**Reason:**
The existing schema is (id, name) and the following two data need to be written:
+I(1, 'zhangsan')
+I(1, 'lisi').
The record 'lisi' was written before 'zhangsan'.The correct result of these two data should be (1, 'zhangsan')

But the data written by Flink in upsert mode is like this:
+I(1, 'zhangsan')
-D(1, 'zhangsan')
+I(1, 'lisi')
-D(1, 'lisi').

When we push down the predicate "name = 'lisi'" to query, the following two data will be filtered:
+I(1, 'lisi')
-D(1, 'lisi').

But the MOR result of these two data is (1, 'lisi').

Therefore, when querying tables in upsert mode, delete data cannot be pushed down using predicates.

### Affects Versions

0.4.0 0.3.x

### What engines are you seeing the problem on?

Core, Spark, Trino

### How to reproduce

Query upsert table with "where" statement

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
> +I(1, 'zhangsan')
+I(1, 'lisi')

Was 'lisi' written before 'zhangsan'?

**Comment by shidayang** [comment]
> > +I(1, 'zhangsan')
> > +I(1, 'lisi')
> 
> Was 'lisi' written before 'zhangsan'?

yes

**Comment by zhoujinsong** [comment]
I followed the step on my docker quick start environment and reproduced the bug:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/7424437/208013463-78e75fb6-fc46-4001-a9cf-cfbe179e30ba.png">

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/7424437/208013376-59fad9a4-c044-44e3-9c4b-08bffd0100eb.png">

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/7424437/208013445-1cae4c46-002f-4f58-b7cd-4623568e9771.png">
