### ISSUE TITLE
[Improvement]: Perhaps a better way of splitting small files for compaction

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#948]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The split small file compact task did not complete within the timeout period, resulting in a failed compaction.

### How should we improve?
For https://github.com/NetEase/arctic/blob/master/ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseIcebergOptimizePlan.java#L94

I have found a way in the iceberg project that might be more appropriate.

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/TableScanUtil.java#L91

Give me some advice.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
Thanks for feeding back!

could you talk a little more about your thoughts? cause I can't quite understand your idea of goals

**Comment by zhongqishang** [comment]
CDC writes in, data is not really large, but the number of files is high. The current splitting logic, which just pack by the sum of `fileScanTask.file()`, could follow my description and consider the expense of merging deletes files in the v2 table.

**Comment by majin1102** [comment]
> @majin1102 CDC writes in, data is not really large, but the number of files is high. The current splitting logic, which just pack by the sum of `fileScanTask.file()`, could follow my description and consider the expense of merging deletes files in the v2 table.
> 
> I think In minor phase, We should minimise the time spent on individual merging tasks. What do you think?

Thanks for sharing your ideas.

I prefer to distinguish your issue into two parts:
1. Why timeout,  right now Arctic optimizer is not robust enough to process very large delete files or too long processing, I don't know the actual reason causing your timeout, maybe it's just too many fragment files to finish within 30 minutes, It would be helpful if you provide your actual input file count. There could be a situation that too many delete records lead to optimizer OOM, and this would be improved in #949 

2. Planning optimization, yes, there are some actual improvements could be done in planning procedure.  From my view, there's key difference between iceberg Optimizing planning and Arctic self-optimizing planning: 

    * First,  Iceberg optimizing command(call rerewitexxxx) is a spark job with clear parallellism, so the goal of planning is completing optimizing job under this concurrency. this planning could be positive to minimize time spent on individual task as you said. Taking advantage of all resources is what Iceberg optimizing need to do even there could be some reading overhead wasted and profits in each subtask may be low.
    * Arctic self-optimizing manages all tables into optimizer groups, and each group resources are shared by tables.  Resource allocation would be complicated and must follow certain principles. current Arctic use quota to limit resources a table self-optimizing could use and this actual allocation would be adjusted as new tables created and time going. That's why Arctic must consider planning leading to best earnings each task. Consider this: Table A use 10 threads optimizing for 10 seconds, with resources spent 100 reaching the level of quota 50 and next round Table would be punished for over using resources. or Table A could use 1 threads optimizing for 50s and next round it still could use the same resource. In summary, Iceberg optimizing is a single call while Arctic self-optimizing is continuous and limited by quota.
    * For your scenario,  you are using native Iceberg table without any file index(or auto-bucket in Arctic). Splitting tasks would certain lead to more reading overhead and make each subtask profit lower. However, too long self-optimizing is actually an improvement point. We shall make this faster without consuming too much resource for low quota punishment. Default target-size 128m target may not be good enough for your scenario. I would consider this value within [fragment-ratio, target-size). 
    
What do you say?

It would be very helpful if you provide your actual file sizes and counts

**Comment by zhongqishang** [comment]
@majin1102 
> 1.

The table has been drop by me, according to my memory, the number of files is 17k+ , split into 2 tasks according to 128m and `SELF_OPTIMIZING_EXECUTE_TIMEOUT_DEFAULT` 30min, executed for about 3 or 4 hours and then timed out.

> 2.
Thank you for the detailed explanation.

It is definitely not acceptable for tasks to keep timing out. In this case, the AMS is not optimised successfully and the merge operation is repeatedly triggered.

From my view, the successful execution of a task is likely to outweigh the consumption of resources and the planned optimisation task needs to be completed as much as possible. It only makes sense to optimise resource utilisation on the basis of normal operation.

**Comment by majin1102** [comment]
3 points from our discussion:

1. set default timeout to 180min cause default behaviour should be tolerant
2. make default parallelism to max available resource parallelism and bin-pack size should be within [segment-target-size, target-size), default is [16m, 128m) (we don't need to consider delete files or open-cost here because delete files are always participating in every subtask)
3. future work: considering disable self-optimizing jobs would certainly failed to prevent global self-optimizing hanging

Improvement 1 and 2 could be pushed on first cc @wangtaohz @hzluting 

> @majin1102
> 
> > 
> 
> The table has been drop by me, according to my memory, the number of files is 17k+ , split into 2 tasks according to 128m and `SELF_OPTIMIZING_EXECUTE_TIMEOUT_DEFAULT` 30min, executed for about 3 or 4 hours and then timed out.
> 
> > 
> 
> Thank you for the detailed explanation.
> 
> It is definitely not acceptable for tasks to keep timing out. In this case, the AMS is not optimised successfully and the merge operation is repeatedly triggered.
> 
> From my view, the successful execution of a task is likely to outweigh the consumption of resources and the planned optimisation task needs to be completed as much as possible. It only makes sense to optimise resource utilisation on the basis of normal operation.

**Comment by zhongqishang** [comment]
BTW, Put the default configuration (like `SELF_OPTIMIZING_EXECUTE_TIMEOUT_DEFAULT`) into the `config.yaml`, Will the experience be more friendly.
Now if I want to change some default values I have to hard code them.
What do you think ? @majin1102 @hzluting

**Comment by majin1102** [comment]
> BTW, Put the default configuration (like `SELF_OPTIMIZING_EXECUTE_TIMEOUT_DEFAULT`) into the `config.yaml`, Will the experience be more friendly. Now if I want to change some default values I have to hard code them. What do you think ? @majin1102 @hzluting

Good idea
We could do it  in Settings module with visible editing. Let's consider it in v0.5

**Comment by majin1102** [comment]
> > BTW, Put the default configuration (like `SELF_OPTIMIZING_EXECUTE_TIMEOUT_DEFAULT`) into the `config.yaml`, Will the experience be more friendly. Now if I want to change some default values I have to hard code them. What do you think ? @majin1102 @hzluting
> 
> Good idea We could do it in the Settings module with visible editing. Let's consider it in v0.5
