### ISSUE TITLE
[Bug][core]:The Arctic reader has a serialization problem for the files written by Impala

### ISSUE THREAD

**Issue by hzluting** [NetEase/arctic#954]
### What happened?

When I use the Arctic read data files written by Impala, it throws the error message below.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/5558252/208569628-fdc13950-e6da-46a4-ae63-38adab030614.png">

### Affects Versions

0.3.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@hzluting What is the table format of the table? As Arctic does not provide an impala writer, for now, Is it a mixed-hive format table and impala write into this table with a hive way?

**Comment by hzluting** [comment]
> @hzluting What is the table format of the table? As Arctic does not provide an impala writer, for now, Is it a mixed-hive format table and impala write into this table with a hive way?

Yes, the table format is mixed-hive, and Impala writes into this table using the hive way.
@shidayang had found the reason because the Impala uses the byte serializer for the column with string type. And the Arctic reader is no adaptation.

**Comment by shidayang** [comment]
This is caused by impala writer data type error.
