### ISSUE TITLE
[Bug]: Failed to process files of length 0 when optimizing

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#966]
### What happened?

Flink stream ingestion job committed an equality-delete file of length 0 after failover, then self-optimizing caught an exception when reading this file.

![image](https://user-images.githubusercontent.com/103108928/209749527-fedef3a1-5f58-40d2-b029-d8ea58d3cda3.png)

### Affects Versions

master/0.3.0

### What engines are you seeing the problem on?

Optimizer, Flink

### How to reproduce

1.After Flink job failover, it occasionally commits a file of length 0.
2.Then the self-optimizing will fail, and we can find the exception in optimizer.

### Anything else

I think we should avoid committing a file of length 0, then no exceptions will occur when MOR/Optimizing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
`com.netease.arctic.io.writer.BaseTaskWriter` doesn't check the file size (or row count) when close
```
  @Override
  public void close() throws IOException {
    for (DataWriter<T> dataWriter : dataWriterMap.values()) {
      dataWriter.close();
      completedFiles.add(dataWriter.toDataFile());
    }
    dataWriterMap.clear();
  }
```

**Comment by wangtaohz** [comment]
And I think it's not a good way to fix this problem by skipping the files of length 0 in the optimizer. Although it avoids the exception, the underlying problem is not solved.

**Comment by wangtaohz** [comment]
cc @zhoujinsong @zstraw @shendanfengg

**Comment by zhoujinsong** [comment]
@wangtaohz I do agree that we should not commit an empty file. I will fix this problem in writers.
