### ISSUE TITLE
[Bug]: Arctic KeyedTable's Change files which exceed TTL but not optimized are deleted by mistake

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#967]
### What happened?

After Arctic KeyedTable does not optimize for a long time, and the Change files exceed TTL, these Change files will be deleted by mistake, which will bring data loss.

### Affects Versions

master/0.4.0/

### How to reproduce

1. Create an Arctic KeyedTable
2. Stop the optimizer
3. Write some data into the change store
4. Set table property `change.data.ttl.minutes` to `1`
5. Wait for 1min and after table expire, the change files will be deleted.

### Anything else

The files are deleted by mistake, because the sequence of files is not loaded from the `file_info_cache` table, when `com.netease.arctic.ams.server.service.impl.FileInfoCacheService#getChangeTableTTLDataFiles` is invoked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@wangtaohz I think this is a fetal bug as it may cause a data lost problem.
@wangtaohz  or @hameizi which of you can fix this problem as soon as possible？

**Comment by wangtaohz** [comment]
I have fixed it by PR #968, please take a look.

**Comment by Aitongong** [comment]
Set table property `change.data.ttl.minutes` to 60, change data file is not deleted. Procedure

**Comment by Aitongong** [comment]
arctic 0.4.0 version

**Comment by wangtaohz** [comment]
> Set table property `change.data.ttl.minutes` to 60, change data file is not deleted. Procedure

Change data files are deleted every 1 hour, and change data files can be deleted only if they: 
 - exceed ttl time
 - are optimized

so, you can check if the optimizing for this table is running as expected.

As, you can check the log of `TableExpireService` where the change ttl files are deleted.

**Comment by Aitongong** [comment]
> > Set table property `change.data.ttl.minutes` to 60, change data file is not deleted. Procedure
> 
> Change data files are deleted every 1 hour, and change data files can be deleted only if they:
> 
>     * exceed ttl time
> 
>     * are optimized
> 
> 
> so, you can check if the optimizing for this table is running as expected.
> 
> As, you can check the log of `TableExpireService` where the change ttl files are deleted.

2023-04-14 13:30:44,347 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.utils.ChangeFilesUtil] [] - demo_catalog.ods.dp_index_data delete 80 change files
however, the file is not actually deleted

**Comment by Aitongong** [comment]
> > Set table property `change.data.ttl.minutes` to 60, change data file is not deleted. Procedure
> 
> Change data files are deleted every 1 hour, and change data files can be deleted only if they:
> 
>     * exceed ttl time
> 
>     * are optimized
> 
> 
> so, you can check if the optimizing for this table is running as expected.
> 
> As, you can check the log of `TableExpireService` where the change ttl files are deleted.

I want to add Dingpin wechat group?

**Comment by wangtaohz** [comment]
> 2023-04-14 13:30:44,347 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.utils.ChangeFilesUtil] [] - demo_catalog.ods.dp_index_data delete 80 change files
however, the file is not actually deleted

<img width="990" alt="image" src="https://user-images.githubusercontent.com/103108928/232363183-16707597-dea3-4df6-b0ea-9f10649dbb75.png">

What about these logs?

Also, I have to make sure what do you mean with `the file is not actually deleted`. These files are exist in file system or in current iceberg snapshot?

**Comment by wangtaohz** [comment]
> I want to add Dingpin wechat group?

Wechat group is here
![image](https://user-images.githubusercontent.com/103108928/232364160-5ebb2ecb-a105-4795-bcf0-cc9001e516b0.png)

**Comment by Aitongong** [comment]
> > 2023-04-14 13:30:44,347 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.utils.ChangeFilesUtil] [] - demo_catalog.ods.dp_index_data delete 80 change files
> > however, the file is not actually deleted
> 
> <img alt="image" width="990" src="https://user-images.githubusercontent.com/103108928/232363183-16707597-dea3-4df6-b0ea-9f10649dbb75.png">
> 
> What about these logs?
> 
> Also, I have to make sure what do you mean with `the file is not actually deleted`. These files exist in file system or in current iceberg snapshot?
2023-04-14 13:30:44,347 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.utils.ChangeFilesUtil] [] - demo_catalog.ods.dp_index_data delete 80 change files
2023-04-14 13:30:44,362 INFO [Optimize Plan Thread Queue-1] [com.netease.arctic.utils.CatalogUtil] [] - TableMetaStore use auth config in catalog meta, authType is simple
***
2023-04-14 13:30:44,625 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.service.impl.FileInfoCacheService] [] - insert 0 files into file cache
2023-04-14 13:30:44,704 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.service.impl.FileInfoCacheService] [] - update 80 files in file cache
2023-04-14 13:30:44,705 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.service.impl.FileInfoCacheService] [] - insert 1 snapshot into snapshot cache
2023-04-14 13:30:44,707 INFO [Metastore Scheduled Expire Worker 0] [com.netease.arctic.ams.server.utils.ChangeFilesUtil] [] - demo_catalog.ods.dp_index_data change committed, delete 80 files, complete 80/80
2023-04-14 13:30:44,710 INFO [Metastore Scheduled Expire Worker 0] [org.apache.iceberg.RemoveSnapshots] [] - Expiring snapshots older than: 2023-04-14T12:30:43.952+0800 (1681446643952)
2023-04-14 13:30:44,766 INFO [Metastore Scheduled Expire Worker 0] [org.apache.iceberg.RemoveSnapshots] [] - Committed snapshot changes

**Comment by Aitongong** [comment]
> > I want to add Dingpin wechat group?
> 
> Wechat group is here ![image](https://user-images.githubusercontent.com/103108928/232364160-5ebb2ecb-a105-4795-bcf0-cc9001e516b0.png)

thank

**Comment by wangtaohz** [comment]
> [com.netease.arctic.ams.server.utils.ChangeFilesUtil] [] - demo_catalog.ods.dp_index_data change committed, delete 80 files, complete 80/80

From this log, these files are deleted from current iceberg snapshot, but not from the file system, because they are still used by the history iceberg snapshots. Only if these snapshots are expired, these files could be deleted from file system.

The logs like `Expiring snapshots older than:XXXXX` indicate the snapshots are expired.

**Comment by wangtaohz** [comment]
The scenario you described is different from this issue. We can create a new issue to discuss if your problem is not resolved yet.

**Comment by wangtaohz** [comment]
> From this log, these files are deleted from current iceberg snapshot, but not from the file system, because they are still used by the history iceberg snapshots. Only if these snapshots are expired, these files could be deleted from file system.
> 
> The logs like `Expiring snapshots older than:XXXXX` indicate the snapshots are expired.

We find that delete these 80 files is the last snapshot of the table, so Iceberg will not expire this snapshot, and also these files will not be deleted from file system. 

The way to delete these files from file system is to add new snapshot to the table, like writing new data to the table.

**Comment by Aitongong** [comment]
> > From this log, these files are deleted from current iceberg snapshot, but not from the file system, because they are still used by the history iceberg snapshots. Only if these snapshots are expired, these files could be deleted from file system.
> > The logs like `Expiring snapshots older than:XXXXX` indicate the snapshots are expired.
> 
> We find that delete these 80 files is the last snapshot of the table, so Iceberg will not expire this snapshot, and also these files will not be deleted from file system.
> 
> The way to delete these files from file system is to add new snapshot to the table, like writing new data to the table.

thank it is ok.
