### ISSUE TITLE
[Improvement]:  spark can return all the history records related to a primary key when spark read the change table

### ISSUE THREAD

**Issue by Aireed** [NetEase/arctic#971]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, spark can only read the latest snapshot to read change.  in the CDC scenario, kafka records all historical versions of a record related to a primary key, which can be backtracked by consuming kafka messages; however, we currently cannot get it from the change table by spark. So, if we can read the snapshot list of the change table, we can get all the historical versions of the record identified by the primary key.

### How should we improve?

Can spark support reading snapshot incrementally??

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
The latest snapshot of the change store contains the last 7 days (default value for table property `change.data.ttl.minutes`) of CDC data. 
So I do think reading CDC data from the latest snapshot of change store is okay and meets expectations.

**Comment by Aireed** [comment]
cc @baiyangtx

**Comment by baiyangtx** [comment]
I need to do double check whether the current code is able to handle this demand.

**Comment by baiyangtx** [comment]
> The latest snapshot of the change store contains the last 7 days (default value for table property `change.data.ttl.minutes`) of CDC data. So I do think reading CDC data from the latest snapshot of change store is okay and meets expectations.

Yes, the query on the last snapshot of the change store could meet expectations

**Comment by wangtaohz** [comment]
Although the current snapshot of the change store contains all the CDC data in the last 7 days (ttl), but there is no API to get the CDC data begin from a specific time.

**Comment by wangtaohz** [comment]
> Although the current snapshot of the change store contains all the CDC data in the last 7 days (ttl), but there is no API to get the CDC data begin from a specific time.

`com.netease.arctic.scan.ChangeTableIncrementalScan` provides getting CDC data from the `TransactionId` of each partition, but we still need the relation between `TransactionId` and time from Table API.

**Comment by baiyangtx** [comment]
> Although the current snapshot of the change store contains all the CDC data in the last 7 days (ttl), but there is no API to get the CDC data begin from a specific time.

change store contains 3 meta column,  _transaction_id, _offset, _operation.  currently, the query could filter by a _transaction_id,  and the timestamp of transaction could be viewed on AMS

**Comment by wangtaohz** [comment]
> change store contains 3 meta column, _transaction_id, _offset, _operation. currently, the query could filter by a _transaction_id, and the timestamp of transaction could be viewed on AMS

Got it.

**Comment by Aireed** [comment]
OK, i will close the issue.
